build.gradle

I got the pdf jar deployed to the hmcts bintray so we can drop the dependency on my custom bintray repo.

Depending on HMCTS pdf generator jar

---

src/main/java/uk/gov/hmcts/reform/sendletter/controllers/RootController.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/GetWelcomeControllerTest.java

Azure App Service has "Always On" feature which silently hits "/" root endpoint. Adding welcome message to fix 404 reporting in AppInsights
```
[ ] Yes
[x] No
```

Introduce RootController

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterTest.java

Fix the integration tests by ensuring records are not committed to the test database but rolled back, so that every test starts from a clean state.

Add transactional attribute to SendLetter tests

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/data/model/DbLetter.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumGenerator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/slc/services/steps/getpdf/PdfCreator.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumGeneratorTest.java

Just clears the full package access to letter entity and removes redundant UUID generation
```
[ ] Yes
[x] No
```

Letter cleanup

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

Reverts hmcts/send-letter-service#29
Premature assumption that documentation is the one and only correct way do optional types

Revert "Avoid EmptyResultDataAccessException"

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/FtpClient.java
src/test/java/uk/gov/hmcts/reform/slc/services/steps/sftpupload/FtpClientTest.java

https://tools.hmcts.net/jira/browse/RPE-335
Ignore non-csv files when processing reports, so that those files don't cause processing errors.
```
[ ] Yes
[x] No
```

Ignore non-csv files when processing reports

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sendletter/LocalSftpServer.java

A few of us have seen intermittent errors during ftp related tests: `net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [] and []`
I believe this to be caused by TestContainers, on which I
raised a [bug.](https://github.com/testcontainers/testcontainers-java/issues/626)
We can work around it by removing the problematic shaded SecurityProvider that TestContainers adds and adding one that is not shaded and is in an official signed BouncyCastle jar.

Fix intermittent FTP TransportException in tests

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

- missing `final` on constant
- logging exception

Fix sonar warnings

---

build.gradle

should not report on untested private constructors in utility classes now 🤞

Upgrade jacoco

---

src/main/resources/db/migration/V006__Add_status_column.sql

This script is not applied in any environment, so it can still be changed.
The constraint can only be added after the replacement of the old system - otherwise we'll have downtime (producer unable to save letters).
```
[ ] Yes
[x] No
```

Remove the NOT NULL constraint from letters table

---

src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

This will be needed later to generate pdf file names (file name includes letter id) before zipping and saving to db.
Also changing FTP downtime window so that tests pass :P

Set letter id in code

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/Task.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/TaskSchedule.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

Add the TaskSchedule that is responsible for scheduling of tasks, making use of the SerialTaskRunner to ensure that tasks are not run concurrently.
This approach was taken to avoid making our existing tasks depend on the SerialTaskRunner (and the refactoring of code/tests that would be required).
The TaskSchedule composes our existing tasks with the SerialTaskRunner to ensure that tasks are not run concurrently.
```
[ ] Yes
[x] No
```

Ensure tasks are not run concurrently

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/SerialTaskRunner.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/Task.java

Advisory locks are referenced by number, so we must avoid collisions eg. lock '0' being used for two different purposes within the same application by different libraries.
Instead of referring to locks as a single long, we can refer to them as two ints and treat the first int as a namespace, for which we use a random constant in this change.
```
[ ] Yes
[x] No
```

Namespace Postgres Advisory locks to avoid collisions

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RPE-372
- Changes replicated from https://github.com/hmcts/job-scheduler/pull/76/
- Spring boot doesn't honour db settings without tomcat prefix.
```
[ ] Yes
[ x] No
```

Update DB settings to include tomcat prefix

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/slc/config/PdfConversionConfig.java
src/main/java/uk/gov/hmcts/reform/slc/services/steps/getpdf/IHtmlToPdfConverter.java
src/main/java/uk/gov/hmcts/reform/slc/services/steps/getpdf/PdfCreator.java
src/test/java/uk/gov/hmcts/reform/slc/services/steps/getpdf/PdfCreatorTest.java

Mostly copied from https://github.com/hmcts/send-letter-consumer-service/blob/master/src/test/java/uk/gov/hmcts/reform/slc/services/steps/getpdf/PdfCreatorTest.java
with slight changes:
- no calls to pdf-service api
- no calls to app insights

Add unit test for pdf creator

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/InternalServerException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnauthenticatedException.java

Report log events to AppInsights with correct implementation avoiding "wrong implementation" errors magically appearing.
```
[ ] Yes
[x] No
```

Fix logged event in response exception handler

---

src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppDependency.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppDependencyCommand.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/AuthService.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/AuthServiceTest.java

We never tracked service authentication as a dependency before. Adding unit test for sanity check
```
[ ] Yes
[x] No
```

Add dependency tracking for service authentication

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/TaskSchedule.java
src/main/resources/application.yaml

- increase upload task delay in integration tests (every 1sec instead of every 1ms (sic!)
- make config value name clearer
- reduce wait time in e2e test (failing test would run for full 2min, now 30sec)
- fix code formatting

Scheduled task interval cleanup

---

src/main/java/uk/gov/hmcts/reform/sendletter/encryption/PgpEncryptionUtil.java

https://tools.hmcts.net/jira/browse/RPE-228
- Updated encryption algorithm from Triple DES to AES 256 as 3DES is very slow.
- Symantec also uses AES 256 by default as their encryption algorithm.
- Decryption should not be impacted because of this change.
- Tested Decryption with Symantec and BountyCastle API and works fine.
```
[ ] Yes
[x ] No
```

Updated Encryption algorithm from 3DES to AES 256

---

.travis.yml

Currently, for every open PR (and push) there are 2 travis builds running.
(as both 'build pushed branches' and 'build pushed pull requests' are enabled)
This change should reduce number of builds to 1.
https://stackoverflow.com/a/31882307

Build pushes to master only on travis

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/util/XeroxReportWriter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportParser.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FileNameHelper.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FileNameHelperTest.java

In preparation for naming encrypted files...
Refactored method was always used to generate PDF, format for zip/pgp is different

Cleanup pdf file name generation

---

src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/UnauthorisedSmokeTest.java

Getting method name was causing a NullPointerException due to getEnclosingMethod returning null.
```
[ ] Yes
[x] No
```

Fix NPE in UnauthorisedSmokeTest

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

[Streamed entities should be closed when using hibernate](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-streaming)
This change closes streams when loading Letters in Upload and stale letter tasks.
```
[ ] Yes
[x] No
```

Close hibernate repository streams

---

infrastructure/variables.tf

- Encryption keys were not found in path `secret/dev/cc/send-letter/encryption-key`and sandbox deployment was failing as the key don't exist in that path.
- As per latest VNET pairing we will need sandbox to point to test instead of Dev.
```
[ ] Yes
[ x] No
```

Updated vault env section to test

---

infrastructure/main.tf
infrastructure/test_config.tf
infrastructure/variables.tf

- Updated config to point to CNP s2s.
- Removed duplicate config.
- Successfully deployed on sandbox https://sandbox-build.platform.hmcts.net/job/HMCTS/job/send-letter-service/job/FIX-MULTIPLE-RESOURCE-VAULT-KEYS/
```
[ ] Yes
[ x] No
```

Fixed s2s url and removed duplicate vault keys config

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/SerialTaskRunner.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/SerialTaskRunnerLockingTest.java

Catch SQLExceptions thrown when the SerialTaskRunner unlocks the database lock, since they mask any exceptions thrown by the task.
```
[ ] Yes
[x] No
```

Stop SerialTaskRunner masking task exceptions

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Notes:
- event for mark letters posted task
- metric for upload letters task
- minor cleanup of unchecked exceptions in test cases which are no longer requried
- super minor log event change
Throughout codebase log events are sufficient enough events for app insights. Agent configurations covers essential key points of the applications. Introduced two metric values figuratively 
```
[ ] Yes
[x] No
```

Feature: track events and metrics to AppInsights

---

src/integrationTest/resources/application.yaml

Fails to load app context due to missing config
```
[ ] Yes
[x] No
```

Fix e2e integration tests

---

src/main/resources/application.yaml

I discovered that the connections used to acquire our database locks are being timed out after 60 seconds and closed because they are idle - no queries are run on them while the lock is held.
When the connection is closed the locks are released and another task can run concurrently :(
This change is a mitigation rather than a fix; it works as long as hour tasks take less than 2 hours (which is true for the foreseeable).
In hindsight I was wrong to implement a custom locking solution and should have used an off the shelf job framework, which should probably be the long term plan.
```
[ ] Yes
[ ] No
```

Increase idle DB connection timeout to 2 hours

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/config/SftpConfig.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/helper/FakeFtpAvailabilityChecker.java
src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpAvailabilityChecker.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/IFtpAvailabilityChecker.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

In some cases (quite often on travis) the jobs in e2e test would start before in-memory sftp server was up, thus causing exception which made the tests fail.
This PR introduces `FakeFtpAvailabilityChecker` class (used only in tests) which can be used to control the FTP 'downtime window' and prevent jobs from trying to make a connection to in-memory sftp server.

Bug - delay background jobs in e2e tests

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java

- File name pattern generation logic has changed but functional tests were not updated.This PR updates that.
- PDF file name generation is unchanged so no changes for that.
```
[ ] Yes
[x ] No
```

Updated type for zip/pgp file name for functional tests

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/test_config.tf

- As we have not specified the vault name in our module default naming convention is <product>-<env>.
- As we have s2s in prod and aat and that one use default vault name we get a conflict 409  as `rpe-aat` and `rpe-prod`  already exists in those environment.
```
[ ] Yes
[ x] No
```

Added vault name and vault uri

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LocalSftpServer.java

This fixes the intermittent test failure 'KeyExchange signature verification failed', which I believe is due to a bug in the really old version of sshd-sftp we were using, instead of the up to date sftp
server in sshd-core.
To investigate this I set up a test loop where our FtpClient continually connected and disconnected to a local sshd server.
With the old version of sshd-sftp I would get a KeyExchange exception after a few seconds to a couple of minutes. After upgrading to sshd-core 1.7.0 I was able to run the loop for an hour without any
problems.
```
[ ] Yes
[x] No
```

Upgrade SSHD test SFTP server to 1.7.0

---

infrastructure/variables.tf

Remove default product name from terraform. Jenkins provides the name, based on what's in `Jekinsfile_...`
```
[ ] Yes
[x] No
```

Remove default product name from terraform

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/UnableToLoadPgpPublicKeyException.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtilTest.java

Throw runtime exceptions defined in the encryption module from the util class instead of forcing the clients to handle ambiguous `IOException` and bouncycastle's exception.
```
[ ] Yes
[x] No
```

Simplify pgp util exceptions

---

Jenkinsfile_parameterized

Fix product and component name in Jenkinsfile_parameterized. Those names need to be the same as in Jenkinsfile_CNP.
```
[ ] Yes
[x] No
```

Fix product and component name in Jenkinsfile_parameterized

---

infrastructure/main.tf
infrastructure/variables.tf

Move PostgreSQL database from West Europe to UK South. Also, because the new version of moj-module-postgres allows for it, rename the DB (to something different than `postgres`) and user.
```
[ ] Yes
[x] No
```

Move PostgreSQL database from West Europe to UK South

---

src/main/java/uk/gov/hmcts/reform/sendletter/Application.java

Adds the EnableScheduling annotation to the Application class. I'm not sure why this was working for our v1 application! This fixes all the tests for me.
```
[ ] Yes
[x] No
```

Enable scheduling for spring boot 2

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpDecryptionHelper.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtilTest.java

Before this change, the zip file inside the PGP archive had .pgp instead of .zip extension.

Fix encrypted file extension

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RPE-375
- Currently value of public encryption key is TBD which is now updated with proper pgp key.
- As terraform won't update the value without changing vault path (even if the value is changed in Hashicorp vault)we have to change the path first and next PR will change it back to what it was.
```
[ ] Yes
[ x] No
```

Temporarily changed path for encryption keys

---

lib/AI-Agent.xml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/helper/FtpHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppDependency.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppDependencyCommand.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java

As inspected in production - there is no FTP tracking happening automagically for us. After attempts to apply signature as MS suggests no luck achieved. Going back to old way of just manually tracking the dependency to keep track of this activity
```
[ ] Yes
[x] No
```

Fix FTP dependency tracking

---

src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

- Claim number is included in additional data and currently we don't log it.
- CMC doesn't retain letter id but they have claim number so only way to link to filename is claim number.
- This way when we receive request to delete some files then we can lookup in app insights as the claim number and file name can be linked.
```
[ ] Yes
[ x] No
```

Include additional data in logging as it includes claim number

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
infrastructure/is_down_alert.tf
infrastructure/is_down_alert_action_group.tf
infrastructure/output.tf

- trying to automate pr build by including some dummy email for alert which is required by terraform plan/apply step
- improve alert query
Query overrides requirement of time window in which the alerting condition is checked. Module requires specific window in minutes and only judge by that. Incorporating it in the query by 5 additional windows making the interval equal to 3 hours instead.
Same measurements are taken and every half an hour and summarising to anticipated `is_operational` flag.
Update gives opportunity to increase threshold which can be interpreted as _correct_ for given failure/alert: only stream of them makes valid assumption whether one can question service is down or not
```
[ ] Yes
[x] No
```

[PREVIEW] Update alert query

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java

I thought this was covered in PR pipeline. Have no idea why it failed during the last build #246. Besides, we know we populate with blank page each document so it's kind of obvious
```
[ ] Yes
[x] No
```

[PREVIEW] Bugfix for functional test for pdf endpoint

---

src/smokeTest/resources/letter.json

Set letter type as smoke_tests in the JSON files used for smoke tests

Update letter type for smoke test

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/DocumentZipException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/DuplexException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/FtpException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/InternalServerException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/LetterNotFoundException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/PdfMergeException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/PendingMigrationScriptException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/ReportParsingException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/ServiceNotConfiguredException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/TaskRunnerException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnableToExtractIdFromFileNameException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnauthenticatedException.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnsupportedLetterRequestTypeException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/UnableToLoadPgpPublicKeyException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/UnableToPgpEncryptZipFileException.java

Moving to logging major revision of 4.0.0
The proprietary exceptions have been removed consequently the inheritance has to be removed.
This should also improve performance of the system by vastly reducing the performance impact of logging.

updating to logging 4.0.0

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

Rename service method from `send` to `save` to avoid any confusion in the future.
The service only saves the letter data in the db.
It is later sent by the scheduled job.

Make method name clearer

---

src/functionalTest/resources/application.properties

Job runs every 30 seconds, that leaves 5 seconds for the test file to be sent to FTP in pessimistic scenarios.
Under heavy load, the test message needs to wait for its turn.

Increase max wait time in functional tests

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LocalSftpServer.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

just in case...
Removing the logic of determining the target folder from FTP client.
The caller sends the FTP client service folder that should be used.
When folder for given service is not found, this fact is logged and the client is never called.

Continue processing other files if folder for given file is not configured

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/FlywayConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/FtpConfigProperties.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java

[Implement AKS for send letter service](https://tools.hmcts.net/jira/browse/BPS-399)
Necessary changes to make AKS pass
- flyway strategy config used but not implemented
- private key is not interpreted as valid one
- java app correctness: close open input streams
last one is labelled as boy-scout one
```
[ ] Yes
[x] No
```

Adapt service to AKS builds

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java

Note: the column was made nullable in previous PR
1. Add new column to DB ✅ https://github.com/hmcts/send-letter-service/pull/290
2. Start writing to both old and new column, keep reading from old column ✅ https://github.com/hmcts/send-letter-service/pull/294
3. Copy data from old column to new column ✅ https://github.com/hmcts/send-letter-service/pull/295
4. Start reading from the new column ✅  https://github.com/hmcts/send-letter-service/pull/297
5. **Stop writing to the old column**
6. Delete old column
7. Update REST API (add extra field)

Rename message_id to checksum: Step 5

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FinalPackageFileNameHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

You can magically hit the spot and fail integration test due to indifference between `Timestamp` and `LocalDateTime`/`ZonedDateTime` implementations. Here are examples:
- [dependency bump](https://build.platform.hmcts.net/view/BSP/job/HMCTS_Platform/job/send-letter-service/view/change-requests/job/PR-305/5/)
- [docker image fix](https://build.platform.hmcts.net/view/BSP/job/HMCTS_Platform/job/send-letter-service/view/change-requests/job/PR-307/2)
This hopefully solves the matter
```
[ ] Yes
[x] No
```

Replace `Timestamp`s with `LocalDateTime`s

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java

It used to default to U.S. Letter, 8.5" x 11".
This was OK for pdfs that we generate based on template that service send us, but there is also a new endpoint that accepts pdf (which may use different sizing).

Use previous page size for extra blank page

---

infrastructure/main.tf

- Working build with the change https://sandbox-build.platform.hmcts.net/job/HMCTS_Sandbox_Platform/job/send-letter-service/job/FIX-SPROD/20/
- Using remote state results into below error for prod
```
11:32:10 Error: Error running plan: 1 error(s) occurred:
11:32:10 * local.ase_name: local.ase_name: Resource 'data.terraform_remote_state.core_apps_compute' does not have attribute 'ase_name' for variable 'data.terraform_remote_state.core_apps_compute.ase_name'
```

Derive ase name from core compute environment

---

build.gradle

JUnit4 has been completely removed:
Bonus: also exclude configuration from coverage, similarly as sonarqube has it configured
```
[ ] Yes
[x] No
```

Remove JUnit4

---

src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java

Experienced at least once:
```
Expecting:
<"type_cmc_11042019083317_9b9df43f-ef3d-4c0e-b18e-3c8aaa89495c.pgp">
to be equal to:
<"type_cmc_11042019083318_9b9df43f-ef3d-4c0e-b18e-3c8aaa89495c.pgp">
but was not.
...
```
```
[ ] Yes
[x] No
```

Assure time is the same in test case

---

build.gradle

New vulnerability for XXE attacks [discovered](https://nvd.nist.gov/vuln/detail/CVE-2019-0228). There's next bugfix version available which is not under owasp radar at the moment
```
[ ] Yes
[x] No
```

Bump pdfbox 2.0.14 -> 2.0.15

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/TimeZones.java
src/main/resources/application.yaml

Depending what date it is `Europe/London` fluctuates between **GMT** and **BST**. Attaching zone ids to cron tasks and to ftp availability checks
```
[ ] Yes
[x] No
```

Use `Europe/London` timezone in tasks

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/RestTemplateConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/ThreadPoolConfig.java
src/main/resources/application.yaml

Following [suggestion](https://howtodoinjava.com/spring-restful/resttemplate-httpclient-java-config/) and the fact that app insights tracks http calls made only via apache http, this configuration should provide such functionality
Couple bonus commits just to drag in some super minor amendments
```
[ ] Yes
[x] No
```

Update configuration for RestTemplate

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/config/RestTemplateConfiguration.java

Additional bean for `feign.Client` is apparently required for application insights' agent. Purposefully skipped during #369 😞 
```
[ ] Yes
[x] No
```

Include `ApacheHttpClient` for feign connections

---

Jenkinsfile_CNP

By tracking/scrolling through this hmcts/cnp-jenkins-library#465 looks like `$environment` is used which is `preview` (checking pipeline in jenkins).
Since PRs installed AKS anyway, ~commenting out~ removing `RESOURCE_GROUP` ~to test hypothesis of~ as it ~being~ become obsolete
```
[ ] Yes
[x] No
```

Fix AKS pipeline for PRs

---

lib/AI-Agent.xml

Minor amendment after #381. The guidelines I was looking are mainly for .NET and they use capitalised names. But, guidelines include mixture of languages so some of the point is Java some not, no doubt it was misguiding
- [actual code](https://github.com/Microsoft/ApplicationInsights-Java/blob/c19c952e7879797aeca53a41eaccf3946d6039a1/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/config/XmlAgentConfigurationBuilder.java#L277)
- [guideline](https://github.com/Microsoft/ApplicationInsights-Java/wiki/Configure-Dependecy-Type-in-the-Agent-Configuration)
```
[ ] Yes
[x] No
```

Fix class type attribute used in agent instrumentation

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportsService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ZeroRowFiller.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/TimeZones.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportsServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ZeroRowFillerTest.java

https://tools.hmcts.net/jira/browse/BPS-626
Added service layer for the letters count report.
The Reports Service excludes the test service, adds a row with count "0" when no letters are uplaoded for the services.
```
[ ] Yes
[ x] No
```

Add service layer for the letters count report

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/EmailSenderDisabledTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/Attachment.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/EmailSender.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/jupiter/GreenMailExtension.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/reports/EmailSenderTest.java

[Automate send letter daily report](https://tools.hmcts.net/jira/browse/BPS-627)
Introducing email sender component as stand-alone feature. No knowledge of contents/reports or any body if necessary. Brings in wide enough usage samples in case report does not need attachment but just some html body in there - can be provided by report separately. Or not report at all.
Ideally this should be a tiny library on it's own as similar implementation is in bulk scan project and potentially can be in others due to the nature of implementation introduced here
```
[ ] Yes
[x] No
```

Add email sending feature

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportDisabledTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportTest.java

[Automate send letter daily report](https://tools.hmcts.net/jira/browse/BPS-627)
Incorporate #394 and #392 to send out an email. Which is disabled at the moment. All the changes are non-effective and left for final (next) PR.
This is another set of "purely additions" PR without breaking anything existing. 
```
[ ] Yes
[x] No
```

Introduce daily report for summary of uploaded letters

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportTest.java

[Automate send letter daily report](https://tools.hmcts.net/jira/browse/BPS-627)
As raised in #396, short-circuiting task execution to minimum in case known key component for sending out email is missing. Raising such situation to `error` level.
Tiny bonus: improved/fixed log message
```
[ ] Yes
[x] No
```

Update report by shortcutting execution

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Was removed only from test and integration scope. Smoke and functional tests do not include test compiles and has separate spring boot testing framework there with junit4. 😇 missed in #350
Since #394 new `greenmail` dependency also dragged it in. Currently we don't need junit4 as same (#394) PR introduced custom extension as a replacement for junit4 `Rule`s
-- edit --
#401 - wiremock dependency drags it in too
```
[ ] Yes
[x] No
```

Remove jUnit4 (again)

---

charts/rpe-send-letter-service/values.template.yaml
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportDisabledByComponentTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportDisabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReportTest.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java
src/main/resources/application.yaml

[Automate send letter daily report](https://tools.hmcts.net/jira/browse/BPS-627)
Going through configuration and infrastructure to enable report for prod only. The secrets are not yet created and will confirm once they are by removing the `DO NOT MERGE` label. Will not start creating secrets until PR is not approved as it will confirm that naming is acceptable.
This PR introduces config separation among different beans: both `EmailSender` and `DailyLetterUploadSummaryReport` was dependant on single config value - `spring.mail.host` which is only relevant for former. Report itself should not repeat this so providing 2 conditions: new flag plus condition on `EmailSender` bean being present (it is dependency).
```
[ ] Yes
[x] …
```

Feature: enable daily report task

---

src/main/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java
src/test/resources/controller/stale-letters/stale-letters-response.json

Move the mapping from letter to stale letter from `StaleLetterService` to `StaleLetterController`. The service needs to return letters in order to be usable by `StaleLettersTask` (stale letters don't contain all the information it uses).
```
[ ] Yes
[x] No
```

Move the letter -> stale letter mapping to the controller

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/StaleLetterSearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTaskTest.java

https://tools.hmcts.net/jira/browse/BPS-621
Retrieve stale letters as a list, not a stream. Choosing stream was premature, as it requires transaction. Stale letters endpoint returns all stale letters, so we read all the data, anyway.
```
[ ] Yes
[x] No
```

Retrieve stale letters as a list, not a stream

---

src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java

Ensure proper formatting of ZonedDateTime fields in letter status response. Before this change the length of the millisecond component wasn't constant and integration tests expected a fixed format, failing intermittently.
This is a quick fix to stabilise builds. Should be followed by a proper solution (https://tools.hmcts.net/jira/browse/BPS-639)
```
[ ] Yes
[x] No
```

 Ensure proper formatting of ZonedDateTime fields

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java

to prevent sending 2 emails (from 2 instances)

Extend lock duration for reporting job

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/ThreadPoolConfig.java

Aftermath of #385. Both Microsoft and SpringBoot suggest such configuration but no1 takes into account multiple instances. This PR includes extra bit of config for `TaskScheduler` bean as it did have before.
Another experiment introduced: `AtomicInteger`. This can also be included as a revert in this PR but I would be glad to continue experimenting 🙃
```
[ ] Yes
[x] No
```

Bean-up `TaskScheduler` to avoid separation among instances

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/AspectConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/ThreadPoolConfig.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/TimeZones.java

Fixing timezoned instant used in request telemetry. Keeping timezoned as behind the scenes app insights might use the value. All metrics at the moment are with extra hour 🙂
```
[ ] Yes
[x] No
```

Update schedule duration calculation

---

build.gradle

Contains changes which we don't use:
- log messages
- spring 2.2 testing
- zookeeper changes
- readme updates
```
[ ] Yes
[x] No
```

Bump shedlock library 2.4.0 -> 2.5.0

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java

Took long time to eye on this warning but today it happened. Another PR failed on functional test step just for _good_ measure. Nothing related to the change but occasionally this step fails and simply needs a re-run
Back to this PR - closing PDF document for **actual good** measure 🙂
```
[ ] Yes
[x] No
```

Close open pdf document left behind (fun tests)

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/TracingConfiguration.java

Fixing clash of dependencies which originate from `/health`. This separation will produce clearer results and actual values of dependencies.
Before:
type | name | operation_Name
--- | --- | ---
Http (tracked component) | GET /health | GET /health
SQL | SQL: jdbc:postgresql://rpe-send... | GET /health
SQL | SQL: jdbc:postgresql://rpe-send... | GET /health
Http (tracked component) | GET /health | GET /health
Http (tracked component) | GET /health | GET /health
SQL | SQL: jdbc:postgresql://rpe-send... | GET /health
SQL | SQL: jdbc:postgresql://rpe-send... | GET /health
Http (tracked component) | GET /health | GET /health
SQL | SQL: jdbc:postgresql://rpe-send... | GET /health
Http (tracked component) | GET /health | GET /health
After:
type | name | operation_Name
--- | --- | ---
Health | GET …

Feature: custom health type telemetry processor

---

build.gradle
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sendletter/config/TimeConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java

[Serialise (Local|Zoned)DateTime fields to contain full millisecond component](https://tools.hmcts.net/jira/browse/BPS-639)
To globally apply config we need to introduce `Jackson2ObjectMapperBuilderCustomizer` bean.
Bonus: moving application insights instrumentation key to application properties - allows to run integration tests via IDE if there is such desire
```
[ ] Yes
[x] No
```

Fix jackson2 (Local|Zoned)DateTime serialization

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java

This PR is build on top of https://github.com/hmcts/send-letter-service/pull/449 - should merge that one first.
Extract duplicated test code into existing test suite. As the next step, we can think about splitting the suite into purpose-specific utilities (authentication, SFTP stuff, etc).
These changes are optional. Some of them might be controversial, to if you don't like them, please let me know.
```
[ ] Yes
[x] No
```

Extract duplicated test code into existing test suite

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java

This was logged in `public <T> T runWith(Function<SFTPClient, T> action) {` method
which is called from:
- downloadReports()
- deleteReport()
- listLetters()
- testConnection()

Fix invalid log message

---

src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Load 3 letters to download at a time instead of 10, as a quick solution of OutOfMemoryError. To be replaced by lazy loading of file content.
```
[ ] Yes
[x] No
```

Load 3 letters to download at a time instead of 10

---

infrastructure/variables.tf
src/main/resources/application.yaml

Change FTP file cleanup cron, so that it runs every hour. It doesn't delete files newer than 12h, anyway.
```
[ ] Yes
[x] No
```

Change FTP file cleanup cron, so that it runs every hour

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/TimeConfiguration.java

Recently a test on Travis started failing consistently:
```
uk.gov.hmcts.reform.sendletter.controllers.GetLetterStatusTest
>should_return_200_when_matching_letter_found_in_db() FAILED
{{ java.lang.AssertionError: 
JSON path "$.created_at"
expected: <2019-06-19T10:16:43.932723Z>
but was:  <2019-06-19T10:16:43.932Z>
}}`
```
Probably due to JRE or OS change on travis.

Fix date formatting in tests

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

the string was only used to create an instance of `PGPPublicKey`

Remove unneeded field from letter service

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/main/resources/application.yaml

in preparation for adding a new property for 'upload-letters' job that will indicate which fingerprint should be used when searching for letters to upload.

Update scheduled jobs config format

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java

Those tests have been failing on my 'speed up marking as posted' branch with annoying and unclear
```
Expecting:
<false>
to be equal to:
<true>
```
messages.
Now it will say that letter status was expected to be 'Posted' but was 'Uploaded' etc.

Clean up end-to-end test assertions

---

build.gradle

Hotfix `jackson-databind` 2.9.9 -> 2.9.9.1

---

build.gradle
config/owasp/suppressions.xml

Over time few dependencies were left behind. Recent merge #490 did not include `scp`. Perhaps because dependency manager has enlisted as previous version being latest.
`Rest-assured` has been postponed until manual intervention. Need to register version with extension to make dependencies properly inject.
Another recent development occurred: sonarqube deprecations
Lastly, pitest. Not a frequent tool but it still exists somewhere and, perhaps, QA is using it. Or can use it
```
[ ] Yes
[x] No
```

Update test dependencies

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

The metric can be extracted from the following log (check source code).
Tiny victory achieved - removed direct dependency of `AppInsights` in the uploader task
```
[ ] Yes
[x] No
```

Remove unnecessary letter count metric in upload task

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
charts/rpe-send-letter-service/values.template.yaml
infrastructure/output.tf
src/main/resources/bootstrap.yaml

[Update Jenkinsfiles to solve deprecated vault sets](https://tools.hmcts.net/jira/browse/BPS-775)
After #516 master pipeline broke due to vault outputs being present (https://github.com/hmcts/send-letter-service/commit/f40b4675415d538cee523eda4e30c9c7e53d0788). PRs fail due to reference to `test-` secrets. Shouldn't need to refer to any additional duplicate config and named with `test-*`
```
[ ] Yes
[x] No
```

Fix pipelines: PR, master

---

Dockerfile
Jenkinsfile_CNP
Jenkinsfile_parameterized

[Update Jenkinsfiles to solve deprecated vault sets](https://tools.hmcts.net/jira/browse/BPS-775)
`enableDbMigration` was using output value of `vaultName` which is suppose to be deprecated. Patch applied and function now accepts vault name should you choose to use this step in your pipeline.
During testing of this feature, fixed parameterised Jenkinsfile which had wrong s2s key name enlisted. That's a **bonus** for this PR
```
[ ] Yes
[x] No
```

Fix pipeline db migration step

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/requirements.yaml
charts/rpe-send-letter-service/values.aat.template.yaml
charts/rpe-send-letter-service/values.preview.template.yaml
charts/rpe-send-letter-service/values.yaml
src/main/resources/bootstrap.yaml

[Update send letter service chart to solve deprecation](https://tools.hmcts.net/jira/browse/BPS-779)
Usage of values.template.yaml is deprecated and TTL is until the end of this week
```
[ ] Yes
[x] No
```

Update deprecated chart template usage

---

infrastructure/output.tf

Component is used/preferred in jenkins library anyway - removing this and solving deprecation notice all-together
```
[ ] Yes
[x] No
```

Remove output of `microserviceName`

---

build.gradle

Used by `testcontainers`. Dependency tree after this change:
```bash
1384-+--- org.testcontainers:postgresql:1.12.0
1385-|    \--- org.testcontainers:jdbc:1.12.0
1386-|         \--- org.testcontainers:database-commons:1.12.0
1387-|              \--- org.testcontainers:testcontainers:1.12.0
1388-|                   +--- junit:junit:4.12
1389-|                   |    \--- org.hamcrest:hamcrest-core:1.3
1390-|                   +--- org.slf4j:slf4j-api:1.7.26
1391-|                   +--- org.jetbrains:annotations:17.0.0
1392-|                   +--- javax.annotation:javax.annotation-api:1.3.2
1393:|                   +--- org.apache.commons:commons-compress:1.18 -> 1.19
```
```
[ ] Yes
[x] No
```

Bump commons-compress 1.18 -> 1.19

---

build.gradle

There was never a version in flyway gradle plugin defined and spring boot manager picked whichever it has in configs. Which was 5.2.4
Dependabot will try to bump to 6.0.2 (as of now) but it is not compatible with current spring boot 2.1 series ¯\\\_(ツ)_/¯
```
[ ] Yes
[x] No
```

Remove 'dynamic' version of flyway from `versions` definition

---

infrastructure/main.tf

This was a symlink anyway, using `cnp` instead
```
[ ] Yes
[x] No
```

Use of `moj` prefix is deprecated

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java

This morning we've received 3 instances of exception logs (and email alerts) about Timeout exception. As we were aware some workaround was done for upload task this was actually prior doing any uploads - getting ssh connection established. Timed out while authenticating user. After 3rd failure everything went back to normal.
Reflecting that and though splitting generic `IOException` with separate step which recognises `UserAuthException` and logs appropriate yet short message - similarly as the original catch block statement
```
[ ] Yes
[x] No
```

Split out user auth related IOException for better debug

---

build.gradle

Aligns with spring boot. Follow references in hmcts/bulk-scan-processor#842 and hmcts/bulk-scan-processor#843
```
[ ] Yes
[x] No
```

Bump shedlock 2.5.0 -> 3.0.0

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
src/functionalTest/resources/application.properties

From 45 to 60 seconds.
Also simplified it a bit, sorry ;)

Increase max wait time for files to appear on FTP in functional tests

---

build.gradle
charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/requirements.yaml
charts/rpe-send-letter-service/values.preview.template.yaml
config/owasp/suppressions.xml

- This PR includes Dependabot upgrade for springboot.
- Also will need to include removal of deprecated config for preview.
- Suppression updated to include the new crypto jar version.
```
[ ] Yes
[x ] No
```

Bump org.springframework.boot from 2.2.4.RELEASE to 2.2.5.RELEASE and remove deprecated chart config

---

README.md
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java

A legacy column in DB, it's always set to `FALSE`.
Judging by requests logged in app insights, this models is never used by the clients.
```
[x] Yes
[ ] No
```

Remove has_failed field from response

---

infrastructure/demo.tfvars

https://tools.hmcts.net/jira/browse/BPS-1225
- Mistakenly generic RPE MI was used for send letter which was supposed to used for other rpe services.
- Send letter service has it's own MI so using that one.
```
[ ] Yes
[x ] No
```

Use send letter MI instead of generic RPE MI

---

docker-compose.yml
src/functionalTest/resources/application.properties

https://tools.hmcts.net/jira/browse/DTSBP-35
use non standard ftp port
```
[ ] Yes
[X] No
```

DTBSP-35: use non standard ftp port to prevent conflict on jenkins

---

infrastructure/main.tf

Can't upgrade dbs in-place so creating new staging dbs at v11 - old ones will be deleted.
This only affects the staging dbs - not the main ones!
```
[ ] Yes
[X] No
```

Create new staging dbs v11

---

infrastructure/appinsights.tf

Fix for application_type var in app insights resource

---

src/main/resources/application.yaml

The no fault divorce case orchestration service is a fork of the divorce one. It has a new microservice name so we need to add the mapping. For now it uses the same config/structure as divorce but we may need to change it in the future

Add no fault divorce API to config

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-467
1. Bump org.owasp.dependencycheck from 6.1.2 to 6.1.5
2. Bump au.com.dius.pact from 4.2.2 to 4.2.3
3. Bump org.flywaydb.flyway from 7.7.0 to 7.7.1
4. Bump flyway-core from 7.7.0 to 7.7.1
5. Bump guava from 30.1-jre to 30.1.1-jre
```
[ ] Yes
[X ] No
```

DTSBPS-467: bump lib

---

infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/liveness-alert.tf
infrastructure/pending-letter-alert.tf
infrastructure/stale-letter-alert.tf
infrastructure/state.tf

to fix master build
```
[](https://build.platform.hmcts.net/job/HMCTS_BSP/job/send-letter-service/job/master/679/console#)[](https://build.platform.hmcts.net/job/HMCTS_BSP/job/send-letter-service/job/master/679/console#)08:10:45  Downloading git@github.com:hmcts/cnp-module-storage-account?ref=master for storage_account...
08:10:46  - storage_account in .terraform/modules/storage_account
08:10:46  [Pipeline] fileExists
08:10:46  [Pipeline] sh
08:10:46  + terraform plan -out tfplan -var common_tags={environment="staging",changeUrl="",managedBy="Software Engineering",BuiltFrom="https://github.com/HMCTS/send-letter-service.git",contactSlackChannel="#platops-help",application="core",businessArea="CFT"} -var env=aat -var product=rpe -var-file=aat.tfvars
08:10:50  [31m╷[0m[0m
08:10:50 …
```

upgrade azurerm to fix master pipeline

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.aat.template.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-964
actions-api-key secrets added to rpe-send-letter-prod, rpe-send-letter-aat, rpe-send-letter-demo key vaults.
Currently their values were just copied from the values of reconciliation-report-api-key secret in reform-scan-prod, reform-scan-aat, reform-scan-demo key vaults.
Once process of generation of such api key is clarified - they will be generated.
There will be a PR using these secrets.
```
[ ] Yes
[x] No
```

DTSBPS-964: Added api-key secret

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-989
We receive the processed letters notifications at 10am and the scheduled task to mark letters as "posted" need another hour. So updating the stale letters report cron to send email at 1PM everyday.
```
[ ] Yes
[x] No
```

Update stale letters reports cron (DTSBPS-989)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-1004
State letters endpoint should not return letters with status 'NotSent'.
Fix the repository method ti exclude status 'NotSent'
```
[ ] Yes
[x] No
```

Exclude letters with status 'NotSent' in stale letters (DTSBPS-1004)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnableToReprocessLetterException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterActionService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterActionServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1024
Letters failed to upload to the FTP server are stuck in `FailedToUpload` status.
Add service method to update the letter status as `Created` to try re-uploading the letter to SFTP server.
```
[ ] Yes
[x] No
```

Re-process letters failed to upload to FTP server (DTSBPS-1024)

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyFtpLetterUploadSummaryReportDisabledByComponentTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyFtpLetterUploadSummaryReportDisabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyFtpLetterUploadSummaryReportTest.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyFtpLetterUploadSummaryReport.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyFtpLetterUploadSummaryReportTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1023
Add config to email daily report for FTP uploaded files.
This report is disabled by default. It'll be enabled in Flux config after testing in lower environments.
```
[ ] Yes
[x] No
```

Configure for FTP uploaded files summary daily report (DTSBPS-1023)

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1105
Use scala-library version '2.13.9' to fix CVE-2022-36944
```
[ ] Yes
[x] No
```

Fix scala-library vulnerability (DTSBPS-1105)

---

.gitignore
infrastructure/appinsights.tf
infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/liveness-alert.tf
infrastructure/main.tf
infrastructure/pending-letter-alert.tf
infrastructure/stale-letter-alert.tf

https://tools.hmcts.net/jira/browse/DTSPO-15909
Updating azurerm_application_insights resource and replacing it with module terraform-module-application-insights
This will allow us to migrate Classic Application Insights using https://github.com/hmcts/app-insights-migration-tool as Classic Application Insights will deprecated and will be retired in February 2024.

DTSPO-15909 - migrated Application Insights

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/FACT-1593
making a change where a subfolder /international is created for whichever service folder letters get sent to if a field isInternational is set to true within addtionalData field
```
[ ] Yes
[x] No
```

Add support for international letters

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/launchdarkly/Flags.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/FACT-1593
when a feild for 'isInternational' boolean exists with a true value then the target folder changes to '/<target_folder>/international' from '/<target_folder>'
this is feature flagged under 'FACT-1593-international-post-flag'
```
[ ] Yes
[x] No
```

FACT-1593 Adding international postage support (w/ feature flagging) [DO NOT MERGE]

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/FACT-1593
changing international folder destination to match in filezilla to International. case is different.
Linked to 
https://github.com/hmcts/send-letter-service/pull/2466
```
[ ] Yes
[x] No
```

FACT-1593 'international' folder is meant to be 'International'

---

README.md
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FileNameHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FileNameHelperTest.java

https://tools.hmcts.net/jira/browse/FACT-2138
for sscs when they send isIbca:true in additionalData then add _IB to zip/pgp file name
```
[ ] Yes
[x] No
```

FACT-2138 added changes to add _IB to sscs isIbca prints
