build.gradle
settings.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/test/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/transitions/UploadLetterTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/transitions/UploadLettersTest.java
src/test/resources/application.yaml

Uses the TestContainers library from the functional tests to start a dockerised postgres.

Contain postgres

---

src/test/java/uk/gov/hmcts/reform/sendletter/transitions/UploadLetterTest.java

Remove the flakey FTP upload test and get the tests green for setting up Travis CI.

remove flakey partially implemented ftp test.

---

build.gradle

Minor clean up.
```
[ ] Yes
[x] No
```

Remove unnecessary logging dependencies

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

Making sure exception is not thrown. [documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.nullability.annotations)
```
[ ] Yes
[x] No
```

Avoid EmptyResultDataAccessException

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipFileNameHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/zip/ZippedDoc.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/zip/Zipper.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Move Zip functionality from slc package to sendletter package
```
[ ] Yes
[x] No
```

Move zipper from slc to sendletter package

---

build.gradle

fix project name and path to config classes excluded in coverage report

Update sonar settings

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

https://tools.hmcts.net/jira/browse/RPE-321
Remove PDF content from DB records after uploading
```
[ ] Yes
[x] No
```

Remove PDF content from DB records after uploading

---

src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpAvailabilityCheckerTest.java

Add unit test for FtpAvailabilityChecker

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/slc/services/ReportParser.java
src/main/java/uk/gov/hmcts/reform/slc/services/steps/sftpupload/ParsedReport.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportParserTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java

Do not remove csv if not all rows were parsed

---

src/test/java/uk/gov/hmcts/reform/sendletter/tasks/SerialTaskRunnerLockingTest.java

Improving code coverage.
```
[ ] Yes
[x] No
```

Add unit test for locking mechanism in SerialTaskRunner

---

src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/ConnectionException.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterControllerTest.java

i used to be thrown from code related to service bus queue.

Remove no longer used exception

---

src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ControllerResponseMessage.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnauthorizedException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/AuthService.java
src/main/resources/application.yaml

consumer no longer calls this service

Remove not used code

---

build.gradle

Test quality of tests by mutating the application code and observe how
many mutations get discovered with the tests.
Run with:
`./gradlew pitest`
```
[ ] Yes
[x] No
```

Add PIT mutation testing to Gradle

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/data/migration/V006MigrationScriptTest.java
src/main/resources/db/migration/V006__Add_status_column.sql

This test was polluting the test database with records and not cleaning it up, which can cause other tests to fail.

Clean up DB after migration test

---

src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java

notes:
- removing service bus tests
- simplify set up for future
```
[ ] Yes
[x] No
```

Cleanup AppInsights

---

src/main/java/uk/gov/hmcts/reform/sendletter/data/LetterRepository.java

Methods unreferenced anywhere in current codebase.
```
[ ] Yes
[x] No
```

Remove unused methods from old LetterRepository

---

src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/rootcontroller/GetWelcomeControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java

also cleaned up namespaces for controller tests, sorry (on a separate commit though)

handle letter with pdf errors

---

src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppDependencyCommand.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/FtpClient.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java

Notes:
- move test suite to new package
- include more dependency coverage
- remove not needed autowiring
```
[ ] Yes
[x] No
```

Feature: log FTP dependency

---

infrastructure/main.tf
infrastructure/variables.tf
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/ILetterRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/resources/application.yaml
src/main/resources/db/migration/V009__Add_is_encrypted_column.sql
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/RPE-228
- This PR only deals with below
1. Adding a new column in letter db.
2. Adding feature toggle for enabling/disabling encryption.
3. Update existing code ton include is_encryption enabled field
```
[ ] Yes
[ x] No
```

Added feature toggle and new column for encryption

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/PdfConversionConfig.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/IHtmlToPdfConverter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfCreator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfMerger.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplexPreparatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java

cleanup after https://github.com/hmcts/send-letter-service/pull/107

Create pdf package

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java

Use try with resources where streams are opened.
```
[ ] Yes
[x] No
```

Ensure PGPEncryptionUtil closes streams

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FinalPackageFileNameHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java

Renamed zip file name helper. it how determines the file extension based on `isEncrypted` flag on letter model

generate file name for encrypted letters

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

Clean up logging in upload job

---

infrastructure/main.tf
src/main/resources/application.yaml

Create terraform db_connection_options variable and append to Postgres connection strings including ssl=true.
```
[ ] Yes
[x] No
```

Use SSL on database connections

---

build.gradle

Updated owasp plugin version to the one used by pipeline

---

src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java

Clearing up workspace. Boy scout commit bonus: closing input stream in pdf merger test
```
[ ] Yes
[x] No
```

Remove unused code

---

lib/AI-Agent.xml

Notes:
- automatic tracking for hibernate
- custom tracking for classes
```
[ ] Yes
[x] No
```

Update AI agent config

---

infrastructure/aat.tfvars

Added aat config to point to preprod vault

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FinalPackageFileNameHelper.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java

Realised this could be an issue after seeing screenshot [here](https://tools.hmcts.net/jira/browse/RPE-228)

Remove underscores from letter type in file name

---

docker/flyway/Dockerfile

tiny update avoids the step of downloading postgres client
```
[ ] Yes
[x] No
```

Improve flyway Dockerfile

---

lib/AI-Agent.xml

- Including built in jdbc tracking.
- Including `LetterRepository` interface methods to replace not supported `HIBERNATE` built in feature - not yet bumped to v5
- since it is interface, not entirely sure this will work
```
[ ] Yes
[x] No
```

App insights: DB tracking

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportParser.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

[Ensure enough logging to producer](https://tools.hmcts.net/jira/browse/RPE-311)
There are continuous info logs around each task to assure app is running correctly. Minor minimisation applied by moving ftp availability check prior actual task run.
Since almost all service factors are covered by tasks, the other places are fairly covered by letter creations and built-in tracking: web requests, dependency hits defined in app insights' agent config.
```
[ ] Yes
[x] No
```

Review logging

---

dependency-check-suppressions.xml

[Send Letter Dependency checker step with suppression file](https://tools.hmcts.net/jira/browse/RPE-392)
Additional suppressions besides the usual ones: pgp related: `CVE-2001-0265`, `CVE-2001-0381` and `CVE-2005-0366`
```
[ ] Yes
[x] No
```

Suppress OWASP vulnerabilities

---

.travis.yml
dependency-check-suppressions.xml
src/integrationTest/resources/application.yaml

Temporary solution, to fix the build.

Make job interval in tests longer

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/IFtpAvailabilityChecker.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java

Fix checkstyle issues
```
[ ] Yes
[x] No
```

Fix checkstyle issues

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java

✈️ + no internet = this PR
See comments on diff below.

Clean up jobs code

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java

Added missing file name extension

---

Jenkinsfile_CNP
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf
src/integrationTest/resources/application.yaml
src/main/resources/application.yaml

- Added `Jenkins_CNP` file to build on prod pipeline.
- By default encryption is turned off and scheduling is turned off through `prod.tfvars`.
- Needs to be tested on preview environment which will done once PR is created.
```
[ ] Yes
[x ] No
```

Infra config prod pipeline

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpDecryptionHelper.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtilTest.java

Remove unused parameter

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/InfoTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/info/LetterStatusInfoContributor.java

shows number of letters in given status

Add info endpoint

---

infrastructure/main.tf

Reverts hmcts/send-letter-service#190

Revert "Temporarily changed path for encryption keys"

---

infrastructure/prod.tfvars

https://tools.hmcts.net/jira/browse/RPE-426
```
[ ] Yes
[ x] No
```

Enabled encyrption on prod

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-Reducecapacity

Set nodes capacity on azure

---

dependency-check-suppressions.xml
infrastructure/main.tf

Use the master branch of postres terraform module. The branch referenced so far (moving postgres to UK South) has been merged into master (https://github.com/hmcts/moj-module-postgres/pull/22).
Also, suppress a PostgreSQL's adminpack-related check.
```
[ ] Yes
[x] No
```

Use the master branch of postres terraform module

---

dependency-check-suppressions.xml

Add d3.js suppression

---

infrastructure/main.tf
infrastructure/variables.tf

Add common tags so previews get shut down
```
[ ] Yes
[ ] No
```

[SKIP-PREVIEW] Add preview tags

---

infrastructure/appinsights.tf
infrastructure/is_down_alert.tf
infrastructure/is_down_alert_action_group.tf
infrastructure/variables.tf

[Configure alerting for send letter service](https://tools.hmcts.net/jira/browse/RPE-689)
As part of alert module, appinsights resource had to be extracted from webapp module. 
```
[ ] Yes
[x] No
```

[PREVIEW] Feature service up/down alert

---

infrastructure/is_down_alert_action_group.tf
infrastructure/main.tf

Don't merge before https://github.com/hmcts/send-letter-service/pull/206
https://tools.hmcts.net/jira/browse/RPE-544
Remove (Hashicorp) vault provider config from infrastructure code. We're not using Hashicorp Vault anymore.
```
[ ] Yes
[x] No
```

[PREVIEW] Remove (Hashicorp) vault provider config from infrastructure code

---

config/owasp/suppressions.xml

Similar to https://github.com/hmcts/bulk-scan-processor/pull/213 from earlier today

Add dependency check suppressions

---

src/main/resources/application.yaml

divorce_service_folders

---

src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java

changed from previously used https://httpstatuses.com/422

Return 403 Forbidden when service is not configured

---

src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java

Missing test for https://tools.hmcts.net/jira/browse/BPS-423

Add test for v2 controller

---

Dockerfile

Copy/Paste mis-use while #273 
```
[ ] Yes
[x] No
```

Bugfix: incorrect port exposed

---

src/main/resources/application.yaml

Include `PROBATE` configuration
```
[ ] Yes
[x] No
```

Probate service folders

---

src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

Sonar still reports as low coverage even though every PR hits 90+. Mostly exceptions are not covered. Going step by step with this one until reached desired outcome.
> Coverage on New Code
> 78.6%
```
[ ] Yes
[x] No
```

Improve branch coverage in `SendLetterService`

---

Jenkinsfile_CNP
kubernetes/deployment.template.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java

[Implement AKS for send letter service](https://tools.hmcts.net/jira/browse/BPS-399)
Re-creating #274. Branch deleted so could not re-open it.
As discussed, we need this to get out so to help future development. Once we have planned the move to helm charts (it is in our backlog) - different PR will be open. Even with a claim "it is so simple and nice" pr (#287) build failed with some syntactics error so parking it to be able to move forward with other tasks
```
[ ] Yes
[x] No
```

Feature: AKS builds

---

src/main/resources/db/migration/V012__Copy_messageId_to_checksum.sql

1. Add new column to DB ✅ https://github.com/hmcts/send-letter-service/pull/290
2. Start writing to both old and new column, keep reading from old column ✅ https://github.com/hmcts/send-letter-service/pull/294
3. **Copy data from old column to new column**
4. Start reading from the new column + stop writing to the old column
5. Delete old column
After previous PR, all new rows will have checksum in the new column (as well as in the old one).
This migration fixes old rows.

Rename message_id to checksum: step 3

---

src/main/resources/db/migration/V014__Remove_message_id_column.sql

After previous PRs, it's no longer used.
1. Add new column to DB ✅ https://github.com/hmcts/send-letter-service/pull/290
2. Start writing to both old and new column, keep reading from old column ✅ https://github.com/hmcts/send-letter-service/pull/294
3. Copy data from old column to new column ✅ https://github.com/hmcts/send-letter-service/pull/295
4. Start reading from the new column ✅  https://github.com/hmcts/send-letter-service/pull/297
5. Stop writing to the old column ✅ https://github.com/hmcts/send-letter-service/pull/298
6. **Delete old column**
7. Update REST API (add extra field)

Remove message_id column

---

Dockerfile

Update to more stable version
```
[ ] Yes
[x] No
```

Update docker file source image

---

build.gradle
config/owasp/suppressions.xml

Our good friend dependabot tried (#309 #310 #311 #312 #313 #320 #321) and was declined. Just combining these updates into one:
- sshd library says "have bouncycastle updated"
- sshd library is test scope
- updating bouncycastle library
Giving last point ^ this is good candidate to do some extra testing by QA on some environment before merging
```
[x] Yes
[x] No
```

Update suppressed group dependencies

---

charts/rpe-send-letter-service/values.template.yaml

Disable persistent storage in Helm chart to avoid unnecessary persistent volumes
```
[ ] Yes
[x] No
```

disable persistent storage in Helm chart

---

.github/stale.yml

Add hmcts bot config for staleness
```
[ ] Yes
[x] No
```

Add stale.yml config

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FileInfo.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/ServiceFolderMapping.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java

Not scheduled/used yet.
https://tools.hmcts.net/jira/browse/BPS-578

Add service for deleting old files

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/BPS-578
Run the service created in https://github.com/hmcts/send-letter-service/pull/334 every day at 5am to delete files that are older than 12 hours (on AAT only)

Clean up old files on AAT periodically

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.template.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

Changing DB passwords mapping to be able to deploy in flux
https://tools.hmcts.net/jira/browse/RPE-1014
Changing DB passwords mapping to be able to deploy in flux
```
[ ] Yes
[x] No
```

Changing DB passwords mapping to be able to deploy in flux

---

src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsRequest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/resources/controller/letter/v1/letter-with-multiple-docs.json

https://tools.hmcts.net/jira/browse/BPS-594

Increase max document count

---

infrastructure/main.tf

Pass common_tags to key-vault module. This is a required parameter now.
```
[ ] Yes
[x] No
```

Pass common_tags to key-vault module

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/rootcontroller/GetWelcomeControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/data/migration/DbMigrationFilesTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/data/migration/FlywayNoOpStrategyTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/AuthServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplexPreparatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpAvailabilityCheckerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumGeneratorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportParserTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtilTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Converting unit tests to junit5. As you follow the diff you should notice couple of changes in testing framework - this is mandatory and I will expect zero questions about it
```
[ ] Yes
[x] No
```

Feature: JUnit5-up unit tests

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/ApplicationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/InfoTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterWithPdfTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Feature: JUnit5-up integration tests

---

build.gradle
config/owasp/suppressions.xml

New [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2018-1258) discovered on spring security. No fix available.
Bonus: update s2s client, closed #344 😇
```
[ ] Yes
[x] No
```

Fix OWASP vulnerabilities

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/CreateLetterSmokeTest.java
src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/SmokeTestSuite.java
src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/UnauthorisedSmokeTest.java

Feature: JUnit5-up functional and smoke tests

---

src/main/resources/application.yaml

Onboard SSCS team
```
[ ] Yes
[x] No
```

Enable SSCS

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

Updates:
- Spring 2.1.3 -> 2.1.4
- Gradle 5.3 -> 5.3.1
- dependency checker config: disable .NET scan
```
[ ] Yes
[x] No
```

Update spring to 2.1.4

---

infrastructure/variables.tf
src/main/resources/application.yaml

CSV files are uploaded to FTP at 10am.

Adjust cron for jobs related to csv files

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
infrastructure/variables.tf
src/main/resources/application.yaml

- #354 - Spring boot update 2.1.3 -> 2.1.4
- #352 - junit4 removal as a dependency
- #356 - dependabot version bump: `hibernate-types-5` 2.4.2 -> 2.4.3
- #355 - amend cron for ftp report task
- #357 - dependabot version bump: `health-spring-boot-starter` 0.0.3 -> 0.0.4
label **DO NOT MERGE** so we can do it tomorrow (11th April) morning
```
[ ] Yes
[x] No
```

Switch to `master` branch. Catch-up PR

---

build.gradle

- latest pitest (been dragging this one for quite some time now)
- jupiter updates:
- junit 5.4.1 -> 5.4.2
- mockito 2.25.1 -> 2.27.0
```
[ ] Yes
[x] No
```

Update test dependencies

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Solving deprecations:
- archive name setting in `bootJar` task
- class directories setting in `jacocoTestReport`
the rest soft warnings (as inspected in IDE) are IDE specific
```
[ ] Yes
[x] No
```

Update gradle 5.3.1 -> 5.4

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java

Minor changes:
- add extra info to logs
- log which file we start going over and how many letters it has
- include file name if errors/warnings
- if letter is not found in DB, log that fact as *error* (was 'warning') https://tools.hmcts.net/jira/browse/BPS-608

Improve logging when marking letters as posted

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FileToSend.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Moved to model as it was kind of a state of a file. Reduced method arguments to benefit featuring multiple file upload support in the future
```
[ ] Yes
[x] No
```

Move `isSmokeTest` flag to model

---

infrastructure/alert_action_group.tf
infrastructure/liveness-alert.tf

https://tools.hmcts.net/jira/browse/BPS-606
- Added liveness alert and action group config.
- Used similar config/alert email as of bulkscan.
- Will update the PR once tested on sandbox as PR doesn't tests/verify tf changes.
```
[ ] Yes
[x ] No
```

Added liveness and alert action tf config

---

infrastructure/exception-alert.tf

https://tools.hmcts.net/jira/browse/BPS-607
- Added exception alert configuration.
- Used similar config to bulkscan
```
[ ] Yes
[ x] No
```

Add exception alert config

---

src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ReportsController.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LettersCountSummary.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/reports/LettersCountSummaryItem.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/reports/LettersCountSummaryResponse.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportsService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/ReportsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/rootcontroller/GetWelcomeControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java

https://tools.hmcts.net/jira/browse/BPS-626
Added end point for uplaoded letters count report
```
[ ] Yes
[x ] No
```

BPS-626 Added reports end point for uploaded letters count

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/StaleLetterSearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterStatus.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java

https://tools.hmcts.net/jira/browse/BPS-621
Create a method in letter repository to find stale letters. It will be called in a future PR within current story.
```
[ ] Yes
[x] No
```

Create a method in letter repository to find stale letters

---

infrastructure/is_down_alert.tf
infrastructure/state.tf

New alerts recently are created with send letter's own action group. Removing reference to bulk scan remote state
```
[ ] Yes
[x] No
```

Remove reference to bulk scan remote state

---

src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sendletter/config/TimeConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/StaleLetter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/TimeZones.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-621
Create a service for retrieving stale letters from the database.
```
[ ] Yes
[x] No
```

Create a service for retrieving stale letters

---

src/main/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/StaleLetterResponse.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterControllerTest.java
src/test/resources/controller/stale-letters/stale-letters-response.json

https://tools.hmcts.net/jira/browse/BPS-621
Create an endpoint for retrieving stale letters
```
[ ] Yes
[x] No
```

Create an endpoint for retrieving stale letters

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/BankHolidaysClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/response/Event.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/response/Holidays.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/BankHolidaysClientTest.java

It will be used to fetch holidays from https://www.gov.uk/bank-holidays/england-and-wales.json

Add client for holidays api

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/ReportsServiceConfig.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LettersCountSummary.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportsService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ZeroRowFiller.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportsServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ZeroRowFillerTest.java

https://tools.hmcts.net/jira/browse/BPS-638
Added new config to map db service names to display names on report.
Updated reports service to use the new config.
```
[ ] Yes
[x ] No
```

Added reports service config to map db service name to display name on reports

---

src/main/java/uk/gov/hmcts/reform/sendletter/config/ReportsServiceConfig.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportsService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportsServiceTest.java

https://github.com/hmcts/send-letter-service/pull/408

Service display name cleanup

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java

- log an error if report is not sent out because of invalid app configuration
- remove email title from logs (this job sends only one report, it's clear which one)
Best reviewed with whitespace changes turned off

Reporting job logging cleanup

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java

Aftermath of #377. Had this locally since then and just rebased now
```
[ ] Yes
[x] No
```

Convert delete functionality to single connection base

---

charts/rpe-send-letter-service/requirements.yaml

https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/81
Use new version of Java chart to clear up deployment revision history
```
[ ] Yes
[x] No
```

upgrade java chart

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java

plus better assertions in tests

Simplify repo method

---

infrastructure/stale-letter-alert.tf

[Stale Letter Alert](https://tools.hmcts.net/jira/browse/BPS-609)
```
[ ] Yes
[x ] No
```

Bps 609 stale letter alert

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTaskTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java

[Send letter: clear PDF file content only after the letter is posted](https://tools.hmcts.net/jira/browse/BPS-648)
```
[ ] Yes
[x] No
```

Remove contents after reported as printed

---

Jenkinsfile_CNP
charts/rpe-send-letter-service/values.template.yaml
infrastructure/variables.tf

- Third party supplier has updated their server as a result the finger print which we store needs to be updated.
-  Before we merge this PR could we please confirm the new generated fingerprint is correct.
```
[ ] Yes
[x ] No
```

Updated finger print as supplier has updated server

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java

Log more information in FtpClient. Also, extend the report processing logging by any exception.
```
[ ] Yes
[x] No
```

Log more information in FtpClient

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/entity/BasicLetterInfo.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/StaleLetterControllerTest.java

Query had to be modified as well

Don't pull file content from db for stale letters model

---

infrastructure/variables.tf
src/main/resources/application.yaml

Mark letters as posted every hour

---

infrastructure/aat.tfvars

note that the key is already set on AAT, only feature toggle needs switching

Enable encryption on AAT

---

infrastructure/main.tf

- Added subscription var to db module as it is enforced by Postgres module else build will fail.
- Formatted terraform file
```
[ ] Yes
[x ] No
```

Added subscripition var to db module as it is mandatory going forward

---

src/main/resources/application.yaml

 Adding service folder for financial remedy (#FR-862)

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.template.yaml

Before:
- everytime between 1600 and 1700 any pr build fails
Now:
- just fail last but least minute before midnight. you should be watching movie if not sleeping by then
```
[ ] Yes
[x] No
```

Update downtime window for helm chart (used in PRs)

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java

Help developer to track actual outcome by providing letter ID in exception message
```
[ ] Yes
[x] No
```

Provide letter ID in functional test assertion exception

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterDataAccessService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java

[Optimise marking letters as posted](https://tools.hmcts.net/jira/browse/BPS-690)
Initial PR: #472. Not sure why it was closed as no description left. Re-attempting to put code back in with minimal change possible
```
[ ] Yes
[x] No
```

Don't load full letter when marking as `Posted`

---

build.gradle
config/checkstyle/checkstyle.xml
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

Source dependency:
- pdfbox 2.0.15 -> 2.0.16 bugfixes
Development dependencies:
- junit 5.5.0 -> 5.5.1 (together with platform 1.5.0 -> 1.5.1)
- gradle 5.4.1 -> 5.5.1
- checkstyle 8.18 -> 8.23
- pmd 8.12.0 -> 8.17.0
```
[ ] Yes
[x] No
```

Update all dependencies but bouncycastle

---

build.gradle
config/owasp/suppressions.xml

Release notes are not easy to find. [Here they are](https://www.bouncycastle.org/releasenotes.html)
```
[ ] Yes
[x] No
```

Bump bouncycastle 1.61 -> 1.62

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/requirements.yaml

https://tools.hmcts.net/jira/browse/BPS-748
Use Helm charts from hmctspublic repository
```
[ ] Yes
[x] No
```

Use Helm charts from hmctspublic repository

---

build.gradle
config/checkstyle/checkstyle.xml

Use same configuration as bulk scan processor and orchestrator
```
[ ] Yes
[x] No
```

Bump `checkstyle` to 8.24

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew

Bump gradle 5.5.1 -> 5.6.1

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

- encryption is enable on all envs -> make it the default value
- turn off fingerprint filtering on AAT (in line with other envs)

Clean up env settings

---

config/owasp/suppressions.xml

No fix yet available. Soon there should be a `2.9.10` version released which addresses issues
```
[ ] Yes
[x] No
```

Suppress not yet released jackson-databind fix

---

Dockerfile
build.gradle
config/owasp/suppressions.xml

Fix version has been released 21st
```
[ ] Yes
[x] No
```

Bump jackson-databind 2.9.9.3 -> 2.9.10

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/BPS-781

Remove filtering letters by encryption key fingerprint

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

Changes:
- [pdfbox](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310760&version=12345681)
- [bouncycastle](https://github.com/bcgit/bc-java/blob/master/docs/releasenotes.html)
- [gradle](https://docs.gradle.org/5.6.2/release-notes.html)
```
[ ] Yes
[x] No
```

Update rest of dependencies

---

infrastructure/main.tf
infrastructure/variables.tf
src/main/resources/application.yaml

Removing config for functionality removed in https://github.com/hmcts/send-letter-service/pull/557

Remove no longer needed config

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

Also make it easier to change the batch size for job run

Read one letter from db at a time

---

src/main/java/uk/gov/hmcts/reform/sendletter/model/in/Doc.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsAndNumberOfCopiesRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-830
Continuation of https://github.com/hmcts/send-letter-service/pull/573
This time: service layer.
One more PR left after this one gets merge: controller layer.

Add new letter request format

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

Assign managed identity object IDs to Key Vaults
```
[ ] Yes
[x] No
```

Assign managed identity object IDs to Key Vaults

---

infrastructure/main.tf

add APP-INSTRUMENTATION-KEY to vault
```
[ ] Yes
[x] No
```

add APP-INSTRUMENTATION-KEY to vault

---

charts/rpe-send-letter-service/Chart.yaml

- Upgrade the client side helm version (new mandatory field in preparation for helm 3)
```
[ ] Yes
[ x] No
```

Added new mandatory field in preparation for helm 3

---

Jenkinsfile_CNP

move env after akschartsinstall
```
[ ] Yes
[x] No
```

move env after akschartsinstall

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfCreator.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java

Add blank page to document (if needed) and **then** make X copies of it.

Optimise adding blank pages

---

src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java

Add extra test

---

charts/rpe-send-letter-service/values.aat.template.yaml

disable ENCRYPTION for staging
```
[ ] Yes
[x] No
```

disable ENCRYPTION

---

Jenkinsfile_CNP
charts/rpe-send-letter-service/values.aat.template.yaml
charts/rpe-send-letter-service/values.preview.template.yaml

enable encryption for all env.
```
[ ] Yes
[x] No
```

enable encryption

---

Jenkinsfile_CNP

disable Legacy Deployment On AAT
```
[ ] Yes
[x] No
```

disable Legacy Deployment On AAT

---

build.gradle
config/owasp/suppressions.xml

`jackson-databind` 2.10.0 integrated with Spring Boot 2.2.0. No need to refer to previous versions which every now and then are marked as vulnerable
```
[ ] Yes
[x] No
```

Use jackson-databind from latest spring boot release

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/BPS-868
disable Legacy Deployment
```
[ ] Yes
[x] No
```

disable Legacy Deployment On ALL

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/BPS-868
This PR will remove app service for send letter service on all environments except demo.
```
[ ] Yes
[x] No
```

delete ASE except demo

---

charts/rpe-send-letter-service/values.preview.template.yaml

indent for new helm version
```
[ ] Yes
[x] No
```

indent for new helm version

---

infrastructure/liveness-alert.tf
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/BPS-933
change liveness alert - after  AKS migration it depends on app name
```
[ ] Yes
[x] No
```

change liveness alert - depend on app name

---

build.gradle
config/owasp/suppressions.xml

- Use tomcat 9.0.30 as older version has vulnerabilities.
- Remove unused suppressions.
```
[ ] Yes
[ x] No
```

Update dependencies and remove retired suppressions

---

Jenkinsfile_CNP

TTL 10 days
```
[ ] Yes
[x] No
```

Remove deprecated flag of docker build

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/BPS-1046
Fpla config mapping
```
[ ] Yes
[x] No
```

Fpla onboarding

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java

https://tools.hmcts.net/jira/browse/BPS-1077
```
[ ] Yes
[x] No
```

Update Send letter daily reports csv file title

---

README.md

https://tools.hmcts.net/jira/browse/BPS-1049
Extend README with information useful for onboarding new services
```
[ ] Yes
[x] No
```

Extend README with information useful for onboarding new services

---

build.gradle

Bump shedlock-provider-jdbc-template and shedlock-spring version

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DailyLetterUploadSummaryReport.java

Fix for #669 
```
[ ] Yes
[x] No
```

Fix usage of deprecated annotations

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/PendingLettersController.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/ReportsController.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/StaleLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/PendingLettersControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/ReportsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/StaleLettersTaskTest.java

In preparation for adding a new reporting endpoint (letter statuses) and new alert (pending letters)

Package cleanup

---

src/main/resources/application.yaml

add folder name - FPLA onboarding
```
[ ] Yes
[x] No
```

add folder name - FPLA onboarding

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterFromGivenDaySearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LettersFromGivenDaySearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/BasicLetterInfo.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PendingLettersServiceTest.java

Also adding 'printed_at' to existing model.
https://tools.hmcts.net/jira/browse/BPS-1119

Add repo method for finding letters created on given day

---

src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/LetterListController.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterInfo.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/LetterListControllerTest.java

https://tools.hmcts.net/jira/browse/BPS-1119

Add letter type field to list of letters

---

infrastructure/demo.tfvars

https://tools.hmcts.net/jira/browse/BPS-1225

Added Managed identity for demo

---

infrastructure/demo.tfvars

https://tools.hmcts.net/jira/browse/BPS-1225

Remove ase deployment for demo

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/BPS-1220
```
[ ] Yes
[x] No
```

Add infrastructure for staging database

---

Jenkinsfile_CNP

Removed deprecated flag.
```
[ ] Yes
[x] No
```

Remove deprecated configuration

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.aat.template.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/BPS-1220
- Add staging database secrets to `bootstrap.yaml` file
- add the secrets to `aat` config
```
[ ] Yes
[x] No
```

Add staging db secrets to bootstrap config

---

charts/rpe-send-letter-service/values.aat.template.yaml

- With staging DB being introduced we need to apply migration through app as pipeline won't apply migration to staging DB.
```
[ ] Yes
[x ] No
```

Set flyway migration skipping to false so that app runs it

---

infrastructure/perftest.tfvars
infrastructure/preview.tfvars
infrastructure/saat.tfvars
infrastructure/sprod.tfvars

Add perftest MI

---

build.gradle

Checking over some strange incompatibility with previous PR running locally and on Jenkins. output is not same. Just quickly amending this one for no-brainers
```
[ ] Yes
[x] No
```

Rename(c|C)ompile -> (i|I)mplementation

---

config/owasp/suppressions.xml

- Bumping date to 19th August.
- No longer need to suppress groovy
```
[ ] Yes
[x] No
```

Review suppression file

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LocalSftpServer.java

#740 and #741 are incompatible with integration source code. Will try to resolve with this PR
```
[ ] Yes
[x] No
```

Bump sshd 2.4.0 -> 2.5.0

---

Dockerfile
build.gradle
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/BPS-1296
Upgraded to Java 11. Also bumped rest-assured, junit and mockito. 
Similar to https://github.com/hmcts/bulk-scan-orchestrator/pull/1006 enforced juint 5 to use groovy 3.
Also upgraded gradle.
```
[x] Yes - potentially yes due to using different docker image
[ ] No
```

Upgraded to Java 11

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/BPS-1296
Upgraded gradle and updated properties to avoid any warnings.
```
[ ] Yes
[x] No
```

Upgrade gradle

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/BPS-1296
One suppression removed.
```
[ ] Yes
[x] No
```

Bumped wiremock version and removed handlebars vulnerability suppression

---

build.gradle

Bump tomcat 9.0.35 -> 9.0.37

---

build.gradle

Fix vulnerability reported by owasp

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

It is not used anymore. Clearing this big chunk so I can add more modules here regarding db migration
```
[ ] Yes
[x] No
```

Remove infra config for main app

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

There's a lock on resources and in order to release them we need DevOps. At this stage it is not relevant - I only wanted to to clear my playground. Let's leave everything as is

Revert "Remove infra config for main app"

---

infrastructure/main.tf

[Migrate send letter DB to version 11](https://tools.hmcts.net/jira/browse/BPS-1057)
This PR:
- Creates new DB
- Stores it's secrets in vault
- Replaces staging db to v11. It is only used for testing purposes in pipeline. Can safely nuke it and rebuild from scratch
```
[ ] Yes
[x] No
```

Feature: postgres v11 database(s)

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml
src/main/resources/bootstrap.yaml

[Migrate send letter DB to version 11](https://tools.hmcts.net/jira/browse/BPS-1057)
Follow-up #757 - bootstrap configs to app before starting to use them
```
[ ] Yes
[x] No
```

Add new db (v11) configs

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java

Addressing comment from the past :)

Use new optional method

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/ClearFileContentTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java

https://tools.hmcts.net/jira/browse/BPS-1328

Add repo method for deleting file content of old letters

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java

https://tools.hmcts.net/jira/browse/BPS-1328
Flux changes: https://github.com/hmcts/cnp-flux-config/pull/4832

Add scheduled job for clearing content of old letters

---

Jenkinsfile_CNP
docker/sftp/data/incoming/BULKPRINT/.gitignore

https://tools.hmcts.net/jira/browse/DTSBP-35
Publish sawgger docs
```
[ ] Yes
[ X] No
```

DTSBP-35: publish swagger docs

---

.github/workflows/swagger.yaml
Jenkinsfile_CNP

Switch to github action to publish swagger docs

---

src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsAndNumberOfCopiesRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsRequest.java

https://tools.hmcts.net/jira/browse/DTSBP-7
Add comments for additionalData in documentation
```
[ ] Yes
[X] No
```

DTSBP-7: Add comments for additionalData in documentation

---

build.gradle
charts/rpe-send-letter-service/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBP-44
Spring boot and chart upgrade
```
[ ] Yes
[X] No
```

DTBSP-44: spring boot and chart upgrade

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBP-50
Bump flyway-core from 6.5.3 to 6.5.5
```
[ ] Yes
[x] No
```

DTBSP-50: Bump flyway-core from 6.5.3 to 6.5.5

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBP-86
DTBSP-86: handle exception in DeleteOldFilesTask
```
[ ] Yes
[x] No
```

DTBSP-86: handle exception in DeleteOldFilesTask

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java

https://tools.hmcts.net/jira/browse/DTSBP-83
Returning number of copies requested
```
[ ] Yes
[ X] No
```

DTSBP-83: Returning number of copies requested

---

infrastructure/main.tf
infrastructure/variables.tf

fixes infra wrt webapp module tech debt

---

infrastructure/alert_action_group.tf
infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/liveness-alert.tf
infrastructure/stale-letter-alert.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSBP-97
Fix for Quoted type constraints are deprecated
```
[ ] Yes
[X] No
```

DTSBP-83: Fix for Quoted type constraints are deprecated

---

build.gradle
config/owasp/suppressions.xml

Update owasp gradle plugin

---

src/main/resources/db/migration/V017__Add_index_to_checksum_column.sql

https://tools.hmcts.net/jira/browse/DTSBPS-2
Added - create index on column checksum on flyway migration script.
```
[ ] Yes
[ X] No
```

DTSBPS-2 Add index to checksum column in db

---

README.md
config/owasp/suppressions.xml

Dependency-Analyze Failure:
Fix for Dependency-Analyze Failure:
```
[X] Yes
[ ] No
```

Fix for dependency check

---

config/owasp/suppressions.xml

BTBSP-121
dependencies vulnerabilities
```
[ ] Yes
[ X] No
```

DTSBPS-121 Fix dependencies vulnerabilities

---

build.gradle
config/owasp/suppressions.xml

Fix up suppressions for new version of Spring Boot

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-170
Reverting this bump as it breaking the build
```
[ ] Yes
[ X] No
```

DTSBPS-170: Reverting the postgresql version as it breaking the build

---

build.gradle
charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.preview.template.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-170
Bump postgresql from 42.2.14 to 42.2.17
```
[ ] Yes
[X ] No
```

DTSBPS-170: bump postgresql version 42.2.17 from 42.2.14

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/AsyncConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/AsyncService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/AsyncServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-197
New threadpool for async calls
```
[ ] Yes
[ x] No
```

DTSBPS-197: New threadpool for async calls

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/helper/FtpHelper.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/RetryOnExceptionStrategy.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
src/test/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-4
Throwing errors after maximum retries expire. Added retry mechanism
```
[ ] Yes
[ X] No
```

DTSBPS-4 Throwing errors after maximum retries expire

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

https://tools.hmcts.net/jira/browse/DTSBPS-208
Handle async save exception to avoid LetterNotFoundException
```
[ ] Yes
[x ] No
```

DTSBPS-208: Handle async save exception to avoid LetterNotFoundException

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/ExceptionLetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/ExceptionLetter.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/ExceptionRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/LetterSaveException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/DuplicateLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ExceptionLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/ExecusionService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/resources/db/migration/V020__Handle_exception_letters.sql
src/test/java/uk/gov/hmcts/reform/sendletter/services/ExceptionLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ExecusionServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-208
Handle async save exception to avoid LetterNotFoundException
```
[ ] Yes
[x ] No
```

DTSBP-208: Handle async save exception to avoid LetterNotFoundException

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-238
Increase DB connection poll size
```
[ ] Yes
[X ] No
```

DTSBPS-238: Increase DB connection poll size

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

https://tools.hmcts.net/jira/browse/DTSBPS-41
Added service not found log
```
[ ] Yes
[ x] No
```

DTSBPS-41: Logging service not found error

---

infrastructure/pending-letter-alert.tf
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-34
Alert for Pending Letter
```
[ ] Yes
[x ] No
```

DTSBPS-34: Alert for Pending Letter

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PendingLetterSearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-255
Updating create time to date time
```
[ ] Yes
[ ] No
```

DTSBPS-255: Updating create time to date time

---

infrastructure/aat.tfvars
infrastructure/appinsights.tf
infrastructure/demo.tfvars
infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

fix for staging kv secrets and tf fmt

---

infrastructure/main.tf

Reference module as list as using a count now

---

infrastructure/main.tf
infrastructure/output.tf

This is the first PR for removing unused DBs for send-letter. This removes the now unused PG 9.6 dbs from all envs.
```
[ ] Yes
[X] No
```

Remove unused pg9.6 RPE dbs

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/DelayedPrintService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTask.java

https://tools.hmcts.net/jira/browse/DTSBPS-43
Added missing transaction annotation
```
[ ] Yes
[x ] No
```

DTSBPS-43: Added transational annotation

---

config/owasp/suppressions.xml

Fix for nightly build failed
Fix for nightly build failed
```
[ ] Yes
[ X] No
```

Fix for nightly build failure

---

Jenkinsfile_CNP
build.gradle

use syncBranchesWithMaster
```
[ ] Yes
[x] No
```

use syncBranchesWithMaster

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PendingLetterSearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetter.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Letter.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatus.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusV2.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/resources/db/migration/V021__Returning_number_of_copies_requested.sql
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusV2Test.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-207
Storing number of copies in Json format
```
[ ] Yes
[ x] No
```

DTSBPS-207: Storing number of copies in Json format.

---

charts/rpe-send-letter-service/values.preview.template.yaml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetterTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/resources/db/migration/V022__Drop columns of Duplicate table

https://tools.hmcts.net/jira/browse/DTSBPS-291
Drop columns of Duplicate table
```
[ ] Yes
[ ] No
```

DTSBPS-291: Drop columns of Duplicate table

---

charts/rpe-send-letter-service/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-298
Fixing build
```
[ ] Yes
[ x] No
```

DTSBPS-298: Fixing build

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-298
Fixing pact test failure
```
[ ] Yes
[ x] No
```

DTSBPS-298: Fixing pact test failure

---

README.md
doc/arch/adr/0001-increase-pod-memory-for-oom-error.md
doc/arch/readme.md

Add ADR to docs

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-249
Fixing PDFBOX
```
[ ] Yes
[ X] No
```

DTSBPS-298: Fixing pdfbox version

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LocalSftpServer.java

https://tools.hmcts.net/jira/browse/DTSBPS-320
Fixing sshd libraries
```
[ ] Yes
[ x] No
```

DTSBPS-320: Fixing sshd libraries

---

Jenkinsfile_CNP
charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.aat.template.yaml
charts/rpe-send-letter-service/values.preview.template.yaml
charts/rpe-send-letter-service/values.yaml
infrastructure/output.tf
infrastructure/variables.tf
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-39
```
[ ] Yes
[ X] No
```

DTSBSP-39: moving address to vault

---

infrastructure/main.tf

DTSDSP-355: Terrform fix

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/Application.java

https://tools.hmcts.net/jira/browse/DTSBPS-368
Upgrade spring boot version 2.3.5.RELEASE to 2.4.2
```
[ ] Yes
[x ] No
```

DTSBPS-368:Upgrading spring boot

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-368
Upgrading libraries
```
[ ] Yes
[ x] No
```

DTSBPS-368:Upgrading libraries

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-394
```
[ ] Yes
[ x] No
```

Lib upgrade

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSBPS-394
Removed azurermv2 as this branch has been deleted.
```
[ ] Yes
[ X] No
```

removed branch ref azurermv2

---

build.gradle
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSBPS-397
```
[ ] Yes
[X ] No
```

Upgrade terrform version 2.49.0

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-399
Fixing FTP client failure
```
[ ] Yes
[ X] No
```

DTSBPS-399: Fixing FTP client failure

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTask.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/StaleLettersTask.java

https://tools.hmcts.net/jira/browse/DTSBPS-257
Prevent pending and stale letter alert to executed more than once
```
[ ] Yes
[ X] No
```

Prevent pending and stale letter alert to executed more than once

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfCreator.java

https://tools.hmcts.net/jira/browse/DTSBPS-403
Logging received file size
```
[ ] Yes
[ x] No
```

Dtsbps 403

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/Application.java

https://tools.hmcts.net/jira/browse/DTSBPS-377
@EnableCircuitBreaker annotation is Deprecated
```
[ ] Yes
[ x] No
```

DTSBPS-377: replace circuitBreaker Annotation with EnableHystrix

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DelayPostSearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/StaleLetterSearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/DelayedPrintService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfCreator.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DelayAndStaleReport.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DelayedPrintServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/util/CsvWriterTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-408
Stale letter report - OOM
```
[ ] Yes
[x ] No
```

DTSBPS-408: Preventing load of byte array for report

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-420
Bump lib
```
[ ] Yes
[ x] No
```

DTSBPS-420: bump libraries

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.aat.template.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-448
```
[ ] Yes
[ x] No
```

DTSBPS-448: Springboot configtree setup

---

build.gradle
config/owasp/suppressions.xml

pdfbox vulnerabilities
https://tools.hmcts.net/jira/browse/DTSBPS-453
```
[ ] Yes
[X ] No
```

DTSBPS-453: pdfbox vulnerabilities

---

build.gradle
config/owasp/suppressions.xml
infrastructure/aat.tfvars
infrastructure/data.tf
infrastructure/main.tf
infrastructure/provider.tf
infrastructure/storage-account.tf

Adds MI to create SAS for blob store and read/write to blob store itself

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

Adds a log message to discover who is still using the v1 api request

---

infrastructure/data.tf
infrastructure/main.tf
infrastructure/storage-account.tf

Grant keda MI read access to the SA blobs

---

src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java

DTSBPS-514
Fix Security Application Issues Raised by Fortify
```
[ ] Yes
[X ] No
```

DTSBPS-514: Fix Security Application Issues Raised by Fortify

---

build.gradle

Fix common-io vulnerabilities and bump libs

---

src/main/resources/db/migration/V023__Add_print_table.sql

https://tools.hmcts.net/jira/browse/DTSBPS-522
New table PRINT
```
[ ] Yes
[ X] No
```

DTSBPS-427: Print table

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PrintRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/Print.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/PrintRepository.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java

https://tools.hmcts.net/jira/browse/DTSBPS-525
Print entity and repo
```
[ ] Yes
[x ] No
```

DTSBPS-427: Print entity and repo

---

infrastructure/storage-account.tf

Adds 'new' containers for each service

---

infrastructure/storage-account.tf

Index container names with their name instead of index in tf state file

---

infrastructure/storage-account.tf

remove all containers temporarily

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/PrintControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/integrationTest/resources/print_job_type_documents_missing.json
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ControllerResponseMessage.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/MediaTypes.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/Document.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/PrintRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-529
Print controller integration with service
```
[ ] Yes
[ x] No
```

DTSBPS-529: Print controller integration with service

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PrintRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java

Print controller integration with service
Fixing tests
```
[ ] Yes
[ x] No
```

Dtsbps 529 v4

---

build.gradle
charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/PrintControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/AccessTokenProperties.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/StorageConfiguration.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnableToGenerateSasTokenException.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/PrintJob.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/PrintResponseTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
src/test/resources/print_job_response.json

… the SAS token
https://tools.hmcts.net/jira/browse/DTSBPS-577
Print service integration with blob container
```
[ ] Yes
[ ] No
```

DTSBPS-577: Print service integration with blob container 

---

infrastructure/storage-account.tf
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/util/TestStorageHelper.java
src/integrationTest/resources/docker/docker-compose.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-586
Changes to integration test and added new container - new-bulkprint
```
[ ] Yes
[ ] No
```

DTSBPS-586: Updates to integration and functional test

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/PrintMessageTest.java
src/functionalTest/resources/print_job_case_id_dynamic.json
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/PrintControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterController.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/Document.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/PrintRequest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/PrintJob.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/PrintResponse.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/PrintUploadInfo.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/PrintResponseTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/test/resources/print_job_response.json

https://tools.hmcts.net/jira/browse/DTSBPS-586
Functional test and relevant changes
```
[ ] Yes
[ ] No
```

DTSBPS-586: Functional test and relevant changes

---

charts/rpe-send-letter-service/values.aat.template.yaml

Define the missing keys to be injected in the aat chart

---

src/main/resources/application.yaml

This default value references a non-existent SA

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-618
nf-divorce service name correction
```
[ ] Yes
[x ] No
```

DTSBPS-618:nf-divorce service name correction

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java

DTSBPS 621
bump libraries
```
[ ] Yes
[ x] No
```

Dtsbps 621 bump libraries

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-626
fix spring-vulnerabilities
```
[ ] Yes
[x] No
```

DTSBPS-626: fix spring-vulnerabilities

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadBlobsTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java

DTSBPS-632
spring boot upgrade to 2.5.1
```
[ ] Yes
[x] No
```

DTSBPS-632: spring boot upgrade to 2.5.1

---

build.gradle

Sonar project name

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sendletter/jupiter/GreenMailExtension.java

DTSBPS-653
Bump greenmail from 1.5.13 to 1.6.4
```
[ ] Yes
[x] No
```

DTSBPS-653: Bump greenmail from 1.5.13 to 1.6.4

---

Jenkinsfile_CNP
infrastructure/ithc.tfvars

DTSBPS-267
sync with master
```
[ ] Yes
[ x] No
```

DTSBPS-267: sync with master

---

src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/PendingLettersControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/date/DateCalculatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/BankHolidaysClientTest.java

DTSBPS-661
code compliance security hotspot
```
[ ] Yes
[x] No
```

DTSBPS-661: code compliance security hotspot

---

src/main/resources/application.yaml

Fix folder setup of nfdiv_case_api service
```
[ ] Yes
[x] No
```

Fix folder setup of nfdiv_case_api service

---

build.gradle

na
upgrade libs
```
[ ] Yes
[x ] No
```

upgrade libs

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java

DTSBPS-674
functional test for async call
```
[ ] Yes
[x] No
```

DTSBPS-674: functional test for async call

---

build.gradle

DTSBPS-677
bumping lib
```
[ ] Yes
[x] No
```

DTSBPS-677: bumping lib

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java

DTSBPS-681
fix - intermittent integration test failure
```
[ ] Yes
[x] No
```

DTSBPS-681: fix - intermittent integration test failure

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/in/print/PrintRequestTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplicateLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ExceptionLetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportParserTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipperTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTaskTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/StaleLettersTaskTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/util/ResourceLoader.java

DTSBPS-682
fix - unstable google load resource
```
[ ] Yes
[x] No
```

DTSBPS-682: fix - unstable google load resource

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java

DTSBPS-681
fix - unstable test
```
[ ] Yes
[x] No
```

DTSBPS-681: fix - unstable test

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java

Probate impl
adding logs
```
[ ] Yes
[ x] No
```

adding log message

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

DTSBPS-686
adding fod scan on nightly pipeline
```
[ ] Yes
[ x] No
```

DTSBPS-686: adding fod scan on nightly pipeline

---

Jenkinsfile_nightly

Pass vault name explicitly to fortify function

---

charts/rpe-send-letter-service/Chart.yaml

DTSBPS-691
update chart java version
```
[ ] Yes
[ x] No
```

DTSBPS-691: update chart java version

---

infrastructure/data.tf
infrastructure/preview_vnet.tf
infrastructure/storage-account.tf

Grant access to AAT SA from preview env

---

build.gradle

DTSBPS-697
remove-duplicate-dependencies
```
[ ] Yes
[x ] No
```

DTSBPS-697: remove-duplicate-dependencies

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java

DTSBPS-697
removed peek
```
[ ] Yes
[x ] No
```

DTSBPS-697: removed peek - sonar complains

---

infrastructure/data.tf

DTSBPS-700
add new aat vnet to blob storages
```
[ ] Yes
[x] No
```

DTSBPS-700: add new aat vnet to blob storages

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java

DTSBPS-697
printrequest log
```
[ ] Yes
[x] No
```

DTSBPS-697: printrequest log

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java

DTSBPS-701
Logging page numbers in document
```
[ ] Yes
[x] No
```

DTSBPS-701: logging page numbers in document

---

build.gradle

DTSBPS-703
Bump flywaydb and pact version
```
[ ] Yes
[x] No
```

DTSBPS-703: bump flywaydb and pact version

---

build.gradle

na
bump flyway db and pact version
```
[ ] Yes
[x] No
```

bump flyway db and pact version

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportParser.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplexPreparatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtilTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

DTSBPS-704
fix deprecated method csv withHeader and few sonar code smell
```
[ ] Yes
[x] No
```

DTSBPS-704: fix deprecated method csv withHeader and few sonar code smell

---

.gitignore
infrastructure/data.tf
infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/ithc.tfvars
infrastructure/liveness-alert.tf
infrastructure/main.tf
infrastructure/pending-letter-alert.tf
infrastructure/stale-letter-alert.tf
infrastructure/state.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

DTSBPS-709
Fix warning regarding Azure Provider block
```
[ ] Yes
[x] No
```

DTSBPS-709: Azure Provider block

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FileNameHelper.java

DTSBPS-733
fix code smell
```
[ ] Yes
[x] No
```

DTSBPS-733 fix code smell

---

config/owasp/suppressions.xml

DTSBPS-750
supress-vulnerability-CVE-2020-0822
```
[ ] Yes
[x] No
```

DTSBPS-750: supress-vulnerability-CVE-2020-0822

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/util/CsvReportWriter.java

DTSBPS-750
fix deprecated code
```
[ ] Yes
[x] No
```

DTSBPS-750: fix deprecated code

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadBlobsTask.java
src/main/resources/application.yaml

DTSBPS-754
adding log message
```
[ ] Yes
[x] No
```

DTSBPS-754: adding log message

---

build.gradle

DTSBPS-773
fix spring cve error
```
[ ] Yes
[x] No
```

DTSBPS-773: fix spring cve error

---

build.gradle
infrastructure/data.tf

DTSBPS-775
fix spring cve error
```
[ ] Yes
[x] No
```

DTSBPS-775: fix spring cve error

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized

add BSP slack notification channel 
```
[ ] Yes
[ ] No
```

DTSBPS-782 add BSP slack notification channel 

---

build.gradle

Bump com.github.ben-manes.versions from 0.40.0 to 0.41.0
```
[ ] Yes
[x] No
```

Bump com.github.ben-manes.versions from 0.40.0 to 0.41.0

---

infrastructure/data.tf
infrastructure/storage-account.tf

DTSBPS-857 fix vnet
```
[ ] Yes
[x] No
```

DTSBPS-857 fix vnet

---

infrastructure/data.tf
infrastructure/storage-account.tf
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

DTSBPS-857 remove app_gw subnet
```
[ ] Yes
[x] No
```

DTSBPS-857 remove app_gw subnet

---

infrastructure/perftest_mgmt_subnet.tf
infrastructure/provider.tf
infrastructure/storage-account.tf
infrastructure/variables.tf

grants access to storage account from perftest mgmt subnet

---

build.gradle
charts/rpe-send-letter-service/Chart.yaml

Bump java chart

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-876
Changed NFD folder to NFDIVORCE
```
[ ] Yes
[x] No
```

Fix NFD folder configuration (DTSBPS-876)

---

charts/rpe-send-letter-service/Chart.yaml

bump-java-chart
```
[ ] Yes
[x] No
```

bump-java-chart

---

infrastructure/storage-account.tf

Add containers for preview to connect to

---

infrastructure/preview_vnet.tf

swap to new preview subnets
```
[ ] Yes
[X] No
```

swap to new preview subnets

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java

https://tools.hmcts.net/jira/browse/DTSBPS-881
```
[ ] Yes
[x] No
```

Added logs

---

build.gradle
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/storage-account.tf
infrastructure/variables.tf

Migration of storage accounts from LRS to ZRS

DTSPO-5822 - ZRS Migration

---

infrastructure/appinsights.tf
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSBPS-903
Add tags to send-letter resource group and appinsights
```
[ ] Yes
[x] No
```

DTSBPS-903: add tags to send-letter resource group and appinsights

---

infrastructure/ithc.tfvars

DTSPO-8293
Send letter storage account in ITHC has been migrated to ZRS by Microsoft
```
[ ] Yes
[x] No
```

DTSPO-8293 - Update ithc storage account to ZRS

---

src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ActionController.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/InvalidApiKeyException.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/ActionControllerTest.java
src/test/resources/application.properties

https://tools.hmcts.net/jira/browse/DTSBPS-964
```
[ ] Yes
[x] No
```

DTSBPS-964: Status change controller

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/LetterNotStaleException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-986
Service method to update letter status to 'Created'
```
[ ] Yes
[x] No
```

DTSBPS-986: Add service method to update letter status to Created

---

src/main/resources/db/migration/V024__Add_letter_events_table.sql

https://tools.hmcts.net/jira/browse/DTSBPS-992
Table for events similar to what exist in blob router and processor.
So far it is supposed to be used only for manual changes in 'letters' table. This is why possible values for 'type' field will be MANUALLY_MOVED_TO_CREATED and MANUALLY_MOVED_TO_NOT_SENT.
```
[ ] Yes
[x] No
```

DTSBPS-992: Create table letter_events

---

docker-compose.yml

Used dummy api key in docker-compose

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterEventRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/EventType.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterEvent.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterEventRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-992
```
[ ] Yes
[x] No
```

DTSBPS-992: Audit repo

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-992
```
[ ] Yes
[x] No
```

DTSBPS-992: Call to LetterEventRepository from service layer

---

config/owasp/suppressions.xml

Suppress CVE-2022-34305
```
[ ] Yes
[x] No
```

Suppress CVE-2022-34305

---

src/main/java/uk/gov/hmcts/reform/sendletter/entity/EventType.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterActionService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterActionServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-995
Add method to the Service class to abort letter processing.
```
[ ] Yes
[x] No
```

Add service changes to abort letter processing (DTSBPS-995)

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ActionController.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/ActionControllerTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-995
Create an endpoint for aborting letters by letter ID
```
[ ] Yes
[x] No
```

Endpoint to abort letter (DTSBPS-995)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DelayPostSearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/StaleLetterSearchTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/DelayedPrintService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DelayAndStaleReport.java
src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DelayedPrintServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/reports/DelayAndStaleReportTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1009
- Fix the stale letters report query ([StateLettersSerach.java](src/main/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterService.java) and test)
- fix incorrectly spelt delayed reports 
```
[ ] Yes
[x] No
```

Fix stale letters report and cleanup delayed letters (DTSBPS-1009)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-1024
Fix repository method to include FailedToUpload status 
```
[ ] Yes
[x] No
```

Fix repository method to include FailedToUpload status (DTSBPS-1024)

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java

https://tools.hmcts.net/jira/browse/DTSBPS-1026
```
[ ] Yes
[x] No
```

DTSBPS-1026: Added size to log

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatusEvent.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusV2.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatusTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusV2Test.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1029
```
[ ] Yes
[x] No
```

DTSBPS-1029: Add events

---

src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
src/test/java/uk/gov/hmcts/reform/sendletter/util/CsvWriterTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1023
Write uploaded file info to CSV files split for each service.
```
[ ] Yes
[x] No
```

Write FTP uploaded letters to CSV files (DTSBPS-1023)

---

src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ActionController.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/ActionControllerTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1036
```
[ ] Yes
[x] No
```

controller for marking letters as posted locally  (DTSBPS-1036)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-1041
Update stale letters query to return the pending letters to print and FTP upload failures
```
[ ] Yes
[x] No
```

Fix stale letters query (DTSBPS-1041)

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1057
Add finrem_case_orchestration service for FINREM
```
[ ] Yes
[x] No
```

Add finrem_case_orchestration service (DTSBPS-1057)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterWithPdfTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/sendletter/exception/DuplexException.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/DuplexPreparator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfCreator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/pdf/PdfMerger.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplexPreparatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1054
Added more logs and service, additional data to the Exceptions to identify the failed requests
```
[ ] Yes
[x] No
```

Add logs and error message to the exception (DTSBPS-1054)

---

src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java

https://tools.hmcts.net/jira/browse/DTSBPS-1066
```
[ ] Yes
[x] No
```

Fix Null Pointer Exception in MarkLetterAsPosted task

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/LetterUploadForDisabledServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/config/FtpConfigProperties.java

https://tools.hmcts.net/jira/browse/DTSBPS-1069
Allow configuration to enable or disable services in specific environments.
```
[ ] Yes
[x] No
```

Configuration to enable or disable services (DTSBPS-1069)

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1083
Upgrading version of Jettison to 1.5.0 has not helped to fix the vulnerability
```
[ ] Yes
[x] No
```

DTSBPS-1083: Added suppression

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1079
Whitelist civil-service
```
[ ] Yes
[x] No
```

Add config for civil-service (DTSBPS-1079)

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1079
Rename service name as OCMC (Online Civil Money Claims) for civil-service
```
[ ] Yes
[x] No
```

Update service name for civil-service (DTSBPS-1079)

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PendingLetterSearchTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/PendingLettersServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1088
```
[ ] Yes
[x] No
```

Fix PendingLetters tests (DTSBPS-1088)

---

infrastructure/appinsights.tf

https://tools.hmcts.net/jira/browse/DTSBPS-1090
```
[ ] Yes
[x] No
```

Add app-insights connection string (DTSBPS-1090)

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1090
```
[ ] Yes
[x] No
```

Add secret for app-insights connection string

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1096
Suppress CVE 2022 33915
```
[ ] Yes
[x] No
```

Suppress CVE 2022 33915

---

build.gradle

Reverts hmcts/send-letter-service#1815

Revert "Bump postgresql from 1.17.4 to 1.17.5"

---

infrastructure/data.tf
infrastructure/storage-account.tf

https://tools.hmcts.net/jira/browse/DTSBPS-1118
```
[ ] Yes
[x] No
```

DTSBPS-1118: Removed old cluster subnets

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1108
Update Old files deletion TTL to 7 days until Xerox completes testing
```
[ ] Yes
[x] No
```

Update Old files deletion TTL (DTSBPS-1108)

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1127
```
[ ] Yes
[x] No
```

DTSBPS-1127: Suppressed CVE-2016-1000027

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1135
update the microservice name as `civil_service`
```
[ ] Yes
[x] No
```

Update civil service config (DTSBPS-1135)

---

.github/workflows/swagger.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1147
Fix Github actions
```
[ ] Yes
[x] No
```

Add distribution to github actions (DTSBPS-1147)

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1231
```
[ ] Yes
[x] No
```

DTSBPS-1231: Suppresed CVE-2022-45693, CVE-2022-45685

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterActionService.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterActionServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1234
Update actions endpoint `mark-posted-locally` and `mark-aborted` endpoints to allow changing the letter status for already `Posted` letters. 
```
[ ] Yes
[x] No
```

DTSBPS-1234 Update actions endpoint

---

infrastructure/main.tf

CHG5011002

---

src/main/resources/db/migration/V025__Add_documents_table.sql

https://tools.hmcts.net/jira/browse/DTSBPS-1322
Added new table called documents
```
[ ] Yes
[ ] No
```

DTSBPS-1322: added documents table sql

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderTest.java

DTSBPS-1322 fixing pact test

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderTest.java

https://tools.hmcts.net/jira/browse/FACT-1317
```
[ ] Yes
[x] No
```

FACT-1317: Fix Pact tests

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java

https://tools.hmcts.net/jira/browse/FACT-1317
Update Pact test configuration to create DocumentService bean
```
[ ] Yes
[x] No
```

FACT-1317: Update Pact test configuration

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/PrintMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/DocumentService.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/FACT-1317
```
[ ] Yes
[x] No
```

FACT-1317: Reduce duplicates cutoff time

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/PrintMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java

FACT-1317: Enable functional tests

---

src/main/resources/application.yaml

[PRL-3657](https://tools.hmcts.net/jira/browse/PRL-3657)
Private law onboarding
```
[ ] Yes
[x] No
```

Private law onboarding

---

src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/ExtendedLetterStatus.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

https://tools.hmcts.net/jira/browse/FACT-1386
returning copies data in the form of Map<String, Integer>
```
[ ] Yes
[x] No
```

FACT-1386 copies data to be returned in GET /letters/<id> endpoint

---

charts/rpe-send-letter-service/values.aat.template.yaml
src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/SmokeTestLaunchDarkly.java

https://tools.hmcts.net/jira/browse/FACT-1436
trying to fix master branch getting secret values
```
[ ] Yes
[x] No
```

removed aat chart values for FACT-1436

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java
src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderTest.java

adding to pact test

---

Jenkinsfile_CNP
src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java
src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/launchdarkly/LaunchDarklyClient.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/RecipientsValidator.java
src/test/java/uk/gov/hmcts/reform/sendletter/model/out/v2/LetterStatusV2Test.java

Pact tests

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/ithc.tfvars
infrastructure/main.tf
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSPO-15408
Removes old MI references after new one added
```
[ ] Yes
[ ] No
```

Remove old MI references

---

README.md
build.gradle
charts/rpe-send-letter-service/Chart.yaml
config/owasp/suppressions.xml
docker/database/Dockerfile
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/exception-alert.tf
infrastructure/is_down_alert.tf
infrastructure/ithc.tfvars
infrastructure/liveness-alert.tf
infrastructure/main.tf
infrastructure/pending-letter-alert.tf
infrastructure/perftest.tfvars
infrastructure/prod.tfvars
infrastructure/provider.tf
infrastructure/stale-letter-alert.tf
infrastructure/state.tf
infrastructure/storage-account.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/FACT-1515
- Created new flexible databases
- Infra code setup for storing secrets in key vault
- General format of terraform files
- Updated readme to show how to convert pdf to base64
```
[ ] Yes
[x] No
```

FACT-1515 Postgres flexible servers

---

Dockerfile
build.gradle
docker/database/Dockerfile

https://tools.hmcts.net/jira/browse/FACT-1598
renovate updates
```
[ ] Yes
[x] No
```

Renovate updates

---

charts/rpe-send-letter-service/Chart.yaml
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

https://tools.hmcts.net/jira/browse/FACT-1619
idea is add more logs based on function calls to help figure out whats wrong with errors in demo send letter service
```
[ ] Yes
[x] No
```

FACT-1619 adding more logs to get more info on demo issue

---

infrastructure/main.tf

Update KV to support bulk scan MI so app deployed in BSP namespace can get secrets.
```
[ ] Yes
[x] No
```

FACT-1394 update KV to support bulk scan MI

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1632
Switch to use flex creds by default for DB.
```
[ ] Yes
[x] No
```

FACT-1632 switch to use flex creds

---

charts/rpe-send-letter-service/values.aat.template.yaml

Use flexi STG db for AAT.
```
[ ] Yes
[x] No
```

Update AAT to use flexi stg DB

---

README.md
build.gradle

CVE-2024-1597 - postgres sql injection issue fixed 
```
[ ] Yes
[x] No
```

Fix dependancies ahead of release

---

infrastructure/tf-db-flexible.tf

Force user permissions on DB so we can connect after migration
```
[ ] Yes
[x] No
```

Force user permissions on DB [DO NOT MERGE UNTIL RELEASE]

---

infrastructure/tf-db-flexible.tf
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java

Temp disable func tests & db product change

---

infrastructure/prod.tfvars
infrastructure/tf-db-flexible.tf
infrastructure/variables.tf

Updated storage to use 128gb in prod and keep default in non-prod.
```
[ ] Yes
[x] No
```

Updated storage to use 128gb in prod

---

src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java

Re-enable func tests.
```
[ ] Yes
[x] No
```

Re-enable func tests

---

infrastructure/main.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/FACT-1663
Removes single server dbs and their secrets, also renames the flexible db secrets to a standard format
```
[ ] Yes
[X] No
```

FACT-1663 Remove Single Server

---

charts/rpe-send-letter-service/Chart.yaml
charts/rpe-send-letter-service/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1663
Switches chart values to default ones
```
[ ] Yes
[x] No
```

FACT-1663 Switches chart values to correct ones

---

infrastructure/tf-db-flexible.tf

Removed unneeded config.
```
[ ] Yes
[x] No
```

Removed unneeded config

---

infrastructure/tf-db-flexible-secrets.tf

https://tools.hmcts.net/jira/browse/FACT-1663
Removes the unused secrets
```
[ ] Yes
[x] No
```

FACT-1663 Removes unused secrets

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-1698
All relevant renovate PRs merged in except for:
- Launch Darkly upgrade to version 7 - [Ticket](https://tools.hmcts.net/jira/browse/FACT-1730)
- Flyway Upgrade to version 10 - [Ticket](https://tools.hmcts.net/jira/browse/FACT-1766)
```
[ ] Yes
[x] No
```

Fact 1698 Renovate Dependency Updates

---

README.md

https://tools.hmcts.net/jira/browse/FACT-1674
Adds Overview, Prerequisites and Quick Start sections 
```
[ ] Yes
[x] No
```

FACT-1674 - Makes Updates to Readme

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-1831
fixing cves if possible
```
[ ] Yes
[x] No
```

FACT-1831 CVE fixes

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/config/FlywayConfiguration.java

https://tools.hmcts.net/jira/browse/FACT-1766
upgrade flyway and postrgres
```
[ ] Yes
[x] No
```

FACT-1766 bump flyway and postgresql

---

build.gradle
charts/rpe-send-letter-service/values.aat.template.yaml

https://tools.hmcts.net/jira/browse/FACT-1838
Update to use temp db rather than dedicated stg for aat build.
```
[ ] Yes
[x] No
```

FACT-1838 update to use temp db

---

infrastructure/aat.tfvars
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/FACT-1838
Delete un-used staging DB now AAT spins up temp one during build.
```
[ ] Yes
[x] No
```

FACT-1838 Delete Stg DB

---

Jenkinsfile_CNP
Jenkinsfile_nightly
README.md
docker/database/Dockerfile
docker/sftp/Dockerfile
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/util/TestUploadStorageHelper.java

https://tools.hmcts.net/jira/browse/FACT-1669
changing postgres image
need to change integration code for test container
change atmoz/sftp image
```
[ ] Yes
[x] No
```

FACT-1881 change images to imported ones

---

README.md
infrastructure/appinsights.tf
infrastructure/variables.tf

fixing platops change
```
[ ] Yes
[x] No
```

app insights terraform fix

---

src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
src/main/java/uk/gov/hmcts/reform/sendletter/launchdarkly/Flags.java
src/main/java/uk/gov/hmcts/reform/sendletter/model/in/RecipientsValidator.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumService.java
src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/DocumentServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java

[FACT-2035](https://tools.hmcts.net/jira/browse/FACT-2035)
remove send letter service launchdarkly flags
```
[ ] Yes
[x] No
```

FACT-2035 remove launchdarkly from send letter service [DO NOT MERGE]

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sendletter/launchdarkly/LaunchDarklyClient.java
src/test/java/uk/gov/hmcts/reform/sendletter/launchdarkly/LaunchDarklyClientTest.java

https://tools.hmcts.net/jira/browse/FACT-1730
update LaunchDarkly to version 7.5.0
```
[X] Yes
[ ] No
```

update LaunchDarkly to version 7.5.0

---

src/main/java/uk/gov/hmcts/reform/sendletter/model/in/RecipientsValidator.java

[FACT-2035](https://tools.hmcts.net/jira/browse/FACT-2035)
remove send letter service launchdarkly flags
```
[ ] Yes
[x] No
```

FACT-2035 added back in bit for fixing pact tests

---

Jenkinsfile_CNP

This PR tries to remove the pact test step from the master build pipeline. We can investigate enabling this at another point.
```
[ ] Yes
[x] No
```

removes pact test on step from master jenkins pipeline

---

src/main/resources/db/migration/V028__Add_batch_delete_letters_function.sql

stuffs messing up so just pushing migration for FACT-2041
migration to add function
```
[ ] Yes
[ ] No
```

FACT-2041 added migration only

---

src/main/resources/db/migration/V029__Alter_batch_delete_letters_status_line.sql

https://tools.hmcts.net/jira/browse/FACT-2041
added cron to delete some old letters
```
[ ] Yes
[x] No
```

FACT-2041 added 'Uploaded' to function - status on line 49

---

src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldLettersTask.java
src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldLettersTaskTest.java

Changes
- Prevent multiple tasks running at once
- stop a task that has been running for more than two hours 
- Log the time taken between batches
- TODO: limit batch to 1000 + change to max 7am on weekend

amendments prev multiple tasks running, ensure it stops after 2 hr

---

config/pmd/ruleset.xml
src/integrationTest/java/uk/gov/hmcts/reform/sendletter/util/CsvReportWriter.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
src/main/java/uk/gov/hmcts/reform/sendletter/services/util/FileNameHelper.java
src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FileNameHelperTest.java

https://tools.hmcts.net/jira/browse/FACT-2305
- Adds checking if letter is related to infected blood and adds IB to file name if so
- Update rules in ruleset to new names
```
[ ] Yes
[x] No
```

FACT-2305 - Amend PDF name to include IB

---

src/main/resources/db/migration/V032__Remove_locking_for_function.sql

https://tools.hmcts.net/jira/browse/FACT-2373
Updated the function to remove the lock
```
[ ] Yes
[x] No
```

FACT-2373: Updated function to remove locking

---

build.gradle

dependancy updates
```
[ ] Yes
[x] No
```

FACT-2386 dependancy updates

---

src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java

Add logs to check some stuff
